  CREATE TABLE "ARTICLES_COMMENTS" 
   (	"COMMENT_ID" NUMBER NOT NULL ENABLE, 
	"ARTICLE_ID" NUMBER NOT NULL ENABLE, 
	"PARENT_ID" NUMBER, 
	"TIME" DATE NOT NULL ENABLE, 
	"PERSON_ID" NUMBER, 
	"TEXT" CLOB, 
	 CONSTRAINT "ARTICLES_COMMENTS_PK" PRIMARY KEY ("COMMENT_ID")
	 ) ;
 
