-- add foreign keys
ALTER TABLE "ARTICLES_COMMENTS" ADD CONSTRAINT "ARTICLES_COMMENTS_ARTICLE_FK1" FOREIGN KEY ("ARTICLE_ID") REFERENCES "ARTICLES" ("ARTICLE_ID") ON DELETE CASCADE ENABLE; 
ALTER TABLE "ARTICLES_COMMENTS" ADD CONSTRAINT "ARTICLES_COMMENTS_ARTICLE_FK2" FOREIGN KEY ("PARENT_ID") REFERENCES "ARTICLES_COMMENTS" ("COMMENT_ID") ON DELETE CASCADE ENABLE; 
ALTER TABLE "ARTICLES_COMMENTS" ADD  CONSTRAINT "ARTICLES_COMMENTS_PERSON_FK1" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID") ON DELETE CASCADE ENABLE;