  CREATE TABLE "PBORIK"."ARTICLES" 
   (	"ARTICLE_ID" NUMBER NOT NULL ENABLE, 
	"PERSON_ID" NUMBER NOT NULL ENABLE, 
	"RESEARCH_GROUP_ID" NUMBER, 
	"TITLE" VARCHAR2(150 BYTE), 
	"TEXT" CLOB NOT NULL ENABLE, 
	"TIME" DATE NOT NULL ENABLE, 
	 CONSTRAINT "ARTICLES_PK" PRIMARY KEY ("ARTICLE_ID")
 );