CREATE TABLE "SCENARIO_TYPE_NONSCHEMA" (
  "SCENARIO_ID" NUMBER NOT NULL ENABLE, 
	"SCENARIO_XML" "SYS"."XMLTYPE" , 
  CONSTRAINT "PK_SCENARIO_TABLE_NONSCHEMA"
    PRIMARY KEY ("SCENARIO_ID"), 
  CONSTRAINT "SCENARIO_TYPE_NONSCHEMA_S_FK1"
    FOREIGN KEY ("SCENARIO_ID")
	  REFERENCES "SCENARIO_TYPE_PARENT" ("SCENARIO_ID")
    ON DELETE CASCADE ENABLE
  )  
  XMLTYPE COLUMN "SCENARIO_XML" STORE AS SECUREFILE BINARY XML
  ALLOW NONSCHEMA
  ALLOW ANYSCHEMA;