ALTER TABLE "EXPERIMENT_OPT_PARAM_DEF" ADD "IS_DEFAULT" NUMBER(1,0) default '1' NOT NULL;
ALTER TABLE "FILE_METADATA_PARAM_DEF" ADD "IS_DEFAULT" NUMBER(1,0) default '1' NOT NULL;
ALTER TABLE "HARDWARE" ADD "IS_DEFAULT" NUMBER(1,0) default '1' NOT NULL;
ALTER TABLE "HEARING_IMPAIRMENT" ADD "IS_DEFAULT" NUMBER(1,0) default '1' NOT NULL;
ALTER TABLE "VISUAL_IMPAIRMENT" ADD "IS_DEFAULT" NUMBER(1,0) default '1' NOT NULL;
ALTER TABLE "WEATHER" ADD "IS_DEFAULT" NUMBER(1,0) default '1' NOT NULL;
ALTER TABLE "PERSON_OPT_PARAM_DEF" ADD "IS_DEFAULT" NUMBER(1,0) default '1' NOT NULL;
