ALTER TABLE "HARDWARE" DROP CONSTRAINT "UNIQUE_HARDWARE_DESCRIPTION";
ALTER TABLE "HARDWARE" DROP CONSTRAINT "UNIQUE_HARDWARE_TITLE";
ALTER TABLE "HARDWARE" DROP CONSTRAINT "UNIQUE_HARDWARE_TYPE";
ALTER TABLE "WEATHER" DROP CONSTRAINT "UNIQUE_WEATHER_DESCRIPTION";
ALTER TABLE "WEATHER" DROP CONSTRAINT "UNIQUE_WHEATER_TITLE";
ALTER TABLE "HEARING_IMPAIRMENT" DROP CONSTRAINT "UNIQUE_HARING_DEFECT_DESCRIPTI";
ALTER TABLE "VISUAL_IMPAIRMENT" DROP CONSTRAINT "UNIQUE_EYES_DEFECT_DESCRIPTION";
