

ALTER TABLE ARTEFACT_REMOVING_METHODS_REL 
    ADD CONSTRAINT ARTEFACT_REMOVING_METHODS_REL_ARTEFACT_REMOVING_METHOD_FK FOREIGN KEY 
    ( 
     ARTEFACT_REMOVING_METHOD_ID
    ) 
    REFERENCES ARTEFACT_REMOVING_METHOD 
    ( 
     ARTEFACT_REMOVING_METHOD_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE DISEASE_REL 
    ADD CONSTRAINT DISEASE_REL_DISEASE_FK FOREIGN KEY 
    ( 
     DISEASE_ID
    ) 
    REFERENCES DISEASE 
    ( 
     DISEASE_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ELECTRODE_CONF 
    ADD CONSTRAINT ELECTRODE_CONF_ELECTRODE_LOCATION_FK FOREIGN KEY 
    ( 
     ELECTRODE_LOCATION_ID
    ) 
    REFERENCES ELECTRODE_LOCATION 
    ( 
     ELECTRODE_LOCATION_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ELECTRODE_CONF 
    ADD CONSTRAINT ELECTRODE_CONF_ELECTRODE_SYSTEM_FK FOREIGN KEY 
    ( 
     ELECTRODE_SYSTEM_ID
    ) 
    REFERENCES ELECTRODE_SYSTEM 
    ( 
     ELECTRODE_SYSTEM_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ELECTRODE_LOCATION 
    ADD CONSTRAINT ELECTRODE_LOCATION_ELECTRODE_FIX_FK FOREIGN KEY 
    ( 
     ELECTRODE_FIX_ID
    ) 
    REFERENCES ELECTRODE_FIX 
    ( 
     ELECTRODE_FIX_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ELECTRODE_LOCATION 
    ADD CONSTRAINT ELECTRODE_LOCATION_ELECTRODE_TYPE_FK FOREIGN KEY 
    ( 
     ELECTRODE_TYPE_ID
    ) 
    REFERENCES ELECTRODE_TYPE 
    ( 
     ELECTRODE_TYPE_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ELECTRODE_LOCATION_REL 
    ADD CONSTRAINT ELECTRODE_LOCATION_REL_ELECTRODE_LOCATION_FK FOREIGN KEY 
    ( 
     ELECTRODE_LOCATION_ID
    ) 
    REFERENCES ELECTRODE_LOCATION 
    ( 
     ELECTRODE_LOCATION_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE PHARMACEUTICAL_REL 
    ADD CONSTRAINT PHARMACEUTICAL_REL_PHARMACEUTICAL_FK FOREIGN KEY 
    ( 
     PHARMACEUTICAL_ID
    ) 
    REFERENCES PHARMACEUTICAL 
    ( 
     PHARMACEUTICAL_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE PROJECT_TYPE_REL 
    ADD CONSTRAINT PROJECT_TYPE_REL_PROJECT_TYPE_FK FOREIGN KEY 
    ( 
     PROJECT_TYPE_ID
    ) 
    REFERENCES PROJECT_TYPE 
    ( 
     PROJECT_TYPE_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SOFTWARE_REL 
    ADD CONSTRAINT SOFTWARE_REL_SOFTWARE_FK FOREIGN KEY 
    ( 
     SOFTWARE_ID
    ) 
    REFERENCES SOFTWARE 
    ( 
     SOFTWARE_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE STIMULUS_REL 
    ADD CONSTRAINT STIMULUS_REL_STIMULUS_FK FOREIGN KEY 
    ( 
     STIMULUS_ID
    ) 
    REFERENCES STIMULUS 
    ( 
     STIMULUS_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE STIMULUS_REL 
    ADD CONSTRAINT STIMULUS_REL_STIMULUS_TYPE_FK FOREIGN KEY 
    ( 
     STIMULUS_TYPE_ID
    ) 
    REFERENCES STIMULUS_TYPE 
    ( 
     STIMULUS_TYPE_ID
    ) 
    NOT DEFERRABLE 
;

