/* pridani parametru do data_file */
ALTER TABLE DATA_FILE ADD "DESC" VARCHAR(250);
ALTER TABLE DATA_FILE ADD ANALYSIS_ID INTEGER;

/* pridani laterality */
ALTER TABLE PERSON ADD LATERALITY CHAR(1) CONSTRAINT "FILLED_LATERALITY" CHECK (LATERALITY = 'L' OR LATERALITY='R' OR LATERALITY='X');

/* pridani education level */
ALTER TABLE PERSON ADD EDUCATION_LEVEL_ID INTEGER;

/* pridani par id do experimentu */
ALTER TABLE EXPERIMENT ADD ARTEFACT_ID INTEGER;
ALTER TABLE EXPERIMENT ADD SUBJECT_GROUP_ID INTEGER;
ALTER TABLE EXPERIMENT ADD ELECTRODE_CONF_ID INTEGER;
ALTER TABLE EXPERIMENT ADD DIGITALIZATION_ID INTEGER;






