CREATE TABLE "ELECTRODE_CONF" (
	"ELECTRODE_CONF_ID" INTEGER NOT NULL ,
	"IMPEDANCE" INTEGER NOT NULL ,
	"ELECTRODE_LOCATION_ID" INTEGER NOT NULL ,
	"ELECTRODE_SYSTEM_ID" INTEGER NOT NULL ,
	"DESC_IMG_ID" INTEGER,
PRIMARY KEY ("ELECTRODE_CONF_ID")
)
;
