CREATE TABLE "DIGITALIZATION" (
	"DIGITALIZATION_ID" INTEGER NOT NULL ,
	"GAIN" INTEGER NOT NULL ,
	"FILTER" VARCHAR2(300) NOT NULL ,
	"SAMPLING_RATE" FLOAT NOT NULL ,
PRIMARY KEY ("DIGITALIZATION_ID")
)
;
