CREATE TABLE "ARTEFACT_REMOVING_METHOD" (
	"ARTEFACT_REMOVING_METHOD_ID" INTEGER NOT NULL ,
	"NAME" VARCHAR2 (50) NOT NULL,
	"DESCRIPTION" VARCHAR2(300) NOT NULL,
	"IS_DEFAULT" INTEGER NOT NULL ,
PRIMARY KEY ("ARTEFACT_REMOVING_METHOD_ID") 
) 
;
