CREATE TABLE "ANALYSIS" (
	"ANALYSIS_ID" INTEGER NOT NULL ,
	"EPOCHS_NUM" INTEGER NOT NULL ,
	"PRESTIMULUS_TIME" INTEGER NOT NULL ,
	"POSTSTIMULUS_TIME" INTEGER NOT NULL ,
	"DESC" VARCHAR2(250) NOT NULL,
PRIMARY KEY ("ANALYSIS_ID") 
)
;
