ALTER TABLE "PHARMACEUTICAL_REL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "DISEASE_REL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "PROJECT_TYPE_REL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "STIMULUS_REL" ADD  FOREIGN KEY ("SCENARIO_ID") REFERENCES "SCENARIO" ("SCENARIO_ID");
ALTER TABLE "ARTEFACT_REMOVING_METHODS_REL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "DATA_FILE" ADD  FOREIGN KEY ("ANALYSIS_ID") REFERENCES "ANALYSIS" ("ANALYSIS_ID");
ALTER TABLE "SOFTWARE_REL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "ELECTRODE_LOCATION_REL" ADD  FOREIGN KEY ("ELECTRODE_CONF_ID") REFERENCES "ELECTRODE_CONF" ("ELECTRODE_CONF_ID");

ALTER TABLE "PERSON" ADD  FOREIGN KEY ("EDUCATION_LEVEL_ID") REFERENCES "EDUCATION_LEVEL" ("EDUCATION_LEVEL_ID");
ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("ELECTRODE_CONF_ID") REFERENCES "ELECTRODE_CONF" ("ELECTRODE_CONF_ID");
ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("SUBJECT_GROUP_ID") REFERENCES "SUBJECT_GROUP" ("SUBJECT_GROUP_ID");
ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("ARTEFACT_ID") REFERENCES "ARTEFACT" ("ARTEFACT_ID");
ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("DIGITALIZATION_ID") REFERENCES "DIGITALIZATION" ("DIGITALIZATION_ID");


