/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   Analysis.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;


import cz.zcu.kiv.eegdatabase.data.annotation.SolrField;
import cz.zcu.kiv.eegdatabase.data.annotation.SolrId;
import cz.zcu.kiv.eegdatabase.logic.indexing.IndexField;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * Analysis generated by hbm2java
 */
@Entity
@Table(name = "ANALYSIS")
public class Analysis implements Serializable {

	@SolrId
	private int analysisId;
	private int epochNumber;
	private int prestimulusTime;
	private int poststimulusTime;
	@SolrField(name = IndexField.TEXT)
	private String description;
	private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);

	public Analysis() {
	}

	public Analysis(int epochNumber, int prestimulusTime, int poststimulusTime,
					String description, Set<ResearchGroup> researchGroups) {
		this.epochNumber = epochNumber;
		this.prestimulusTime = prestimulusTime;
		this.poststimulusTime = poststimulusTime;
		this.description = description;
		this.researchGroups = researchGroups;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ANALYSIS_ID", nullable = false, precision = 22, scale = 0)
	public int getAnalysisId() {
		return this.analysisId;
	}

	public void setAnalysisId(int analysisId) {
		this.analysisId = analysisId;
	}

	@Column(name = "EPOCHS_NUM", precision = 22, scale = 0)
	public int getEpochNumber() {
		return this.epochNumber;
	}

	public void setEpochNumber(int epochNumber) {
		this.epochNumber = epochNumber;
	}

	@Column(name = "PRESTIMULUS_TIME", precision = 22, scale = 0)
	public int getPrestimulusTime() {
		return this.prestimulusTime;
	}

	public void setPrestimulusTime(int prestimulusTime) {
		this.prestimulusTime = prestimulusTime;
	}

	@Column(name = "POSTSTIMULUS_TIME", precision = 22, scale = 0)
	public int getPoststimulusTime() {
		return this.poststimulusTime;
	}

	public void setPoststimulusTime(int poststimulusTime) {
		this.poststimulusTime = poststimulusTime;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ANALYSIS_GROUP_REL", joinColumns = {
		@JoinColumn(name = "ANALYSIS_ID", nullable = false, updatable = false)}, inverseJoinColumns = {
		@JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, updatable = false)})
	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}
}
