/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   Artifact.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;



import javax.persistence.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import cz.zcu.kiv.formgen.annotation.Form;
import org.hibernate.annotations.GenericGenerator;

import cz.zcu.kiv.formgen.annotation.FormId;
import cz.zcu.kiv.formgen.annotation.FormItem;
import cz.zcu.kiv.formgen.annotation.PreviewLevel;

/**
 * Artifact generated by hbm2java
 */
@Form
@Entity
@Table(name = "ARTEFACT")
public class Artifact implements java.io.Serializable {

	@FormId
	private int artifactId;
	@FormItem(preview = PreviewLevel.MAJOR)
	private String compensation;
	@FormItem
	private String rejectCondition;
	private Set<Experiment> experiments = new HashSet<Experiment>(0);
	private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);

	public Artifact() {
	}

	public Artifact(String compensation, String rejectCondition,
			Set<Experiment> experiments, Set<ResearchGroup> researchGroups) {
		this.compensation = compensation;
		this.rejectCondition = rejectCondition;
		this.experiments = experiments;
		this.researchGroups = researchGroups;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ARTEFACT_ID", nullable = false, precision = 22, scale = 0)
	public int getArtifactId() {
		return this.artifactId;
	}

	public void setArtifactId(int artifactId) {
		this.artifactId = artifactId;
	}

	@Column(name = "COMPENSATION")
	public String getCompensation() {
		return this.compensation;
	}

	public void setCompensation(String compensation) {
		this.compensation = compensation;
	}

	@Column(name = "REJECT_CONDITION")
	public String getRejectCondition() {
		return this.rejectCondition;
	}

	public void setRejectCondition(String rejectCondition) {
		this.rejectCondition = rejectCondition;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artifact")
	public Set<Experiment> getExperiments() {
		return this.experiments;
	}

	public void setExperiments(Set<Experiment> experiments) {
		this.experiments = experiments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ARTEFACT_GROUP_REL", joinColumns = { @JoinColumn(name = "ARTEFACT_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, updatable = false) })
	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}

}
