/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   ExperimentOptParamValId.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA


import javax.persistence.Embeddable;

/**
 * ExperimentOptParamValId generated by hbm2java
 */
@Embeddable
public class ExperimentOptParamValId  implements java.io.Serializable {

     private int experimentId;
     private int experimentOptParamDefId;

    public ExperimentOptParamValId() {
    }

    public ExperimentOptParamValId(int experimentId, int experimentOptParamDefId) {
       this.experimentId = experimentId;
       this.experimentOptParamDefId = experimentOptParamDefId;
    }
   
    public int getExperimentId() {
        return this.experimentId;
    }
    
    public void setExperimentId(int experimentId) {
        this.experimentId = experimentId;
    }
    public int getExperimentOptParamDefId() {
        return this.experimentOptParamDefId;
    }
    
    public void setExperimentOptParamDefId(int experimentOptParamDefId) {
        this.experimentOptParamDefId = experimentOptParamDefId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExperimentOptParamValId) ) return false;
		 ExperimentOptParamValId castOther = ( ExperimentOptParamValId ) other; 
         
		 return (this.getExperimentId()==castOther.getExperimentId())
 && (this.getExperimentOptParamDefId()==castOther.getExperimentOptParamDefId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getExperimentId();
         result = 37 * result + this.getExperimentOptParamDefId();
         return result;
   }   


}


