package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExperimentOptParamValId generated by hbm2java
 */
@Embeddable
public class ExperimentOptParamValId implements java.io.Serializable {

	private int experimentId;
	private int experimentOptParamDefId;

	public ExperimentOptParamValId() {
	}

	public ExperimentOptParamValId(int experimentId, int experimentOptParamDefId) {
		this.experimentId = experimentId;
		this.experimentOptParamDefId = experimentOptParamDefId;
	}

	@Column(name = "EXPERIMENT_ID", nullable = false, precision = 22, scale = 0)
	public int getExperimentId() {
		return this.experimentId;
	}

	public void setExperimentId(int experimentId) {
		this.experimentId = experimentId;
	}

	@Column(name = "EXPERIMENT_OPT_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)
	public int getExperimentOptParamDefId() {
		return this.experimentOptParamDefId;
	}

	public void setExperimentOptParamDefId(int experimentOptParamDefId) {
		this.experimentOptParamDefId = experimentOptParamDefId;
	}

}
