package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExperimentOptParamDefGroupRel generated by hbm2java
 */
@Entity
@Table(name = "EXPERIMENT_OPT_PARAM_GROUP_REL")
public class ExperimentOptParamDefGroupRel implements java.io.Serializable {

	private ExperimentOptParamDefGroupRelId id;
	private ResearchGroup researchGroup;
	private ExperimentOptParamDef experimentOptParamDef;

	public ExperimentOptParamDefGroupRel() {
	}

	public ExperimentOptParamDefGroupRel(ExperimentOptParamDefGroupRelId id,
			ResearchGroup researchGroup,
			ExperimentOptParamDef experimentOptParamDef) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.experimentOptParamDef = experimentOptParamDef;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "experimentOptParamDefId", column = @Column(name = "EXPERIMENT_OPT_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "researchGroupId", column = @Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)) })
	public ExperimentOptParamDefGroupRelId getId() {
		return this.id;
	}

	public void setId(ExperimentOptParamDefGroupRelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, insertable = false, updatable = false)
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPERIMENT_OPT_PARAM_DEF_ID", nullable = false, insertable = false, updatable = false)
	public ExperimentOptParamDef getExperimentOptParamDef() {
		return this.experimentOptParamDef;
	}

	public void setExperimentOptParamDef(
			ExperimentOptParamDef experimentOptParamDef) {
		this.experimentOptParamDef = experimentOptParamDef;
	}

}
