package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

/**
 * ExperimentOptParamVal generated by hbm2java
 */
//@Entity
//@Indexed
public class ExperimentOptParamVal implements java.io.Serializable {
//@DocumentId
  private ExperimentOptParamValId id;
  private Experiment experiment;
  private ExperimentOptParamDef experimentOptParamDef;
//  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "PARAMVALUE")}) //use a different field name
  private String paramValue;

  public ExperimentOptParamVal() {
  }

  public ExperimentOptParamVal(ExperimentOptParamValId id, Experiment experiment, ExperimentOptParamDef experimentOptParamDef, String paramValue) {
    this.id = id;
    this.experiment = experiment;
    this.experimentOptParamDef = experimentOptParamDef;
    this.paramValue = paramValue;
  }

  public ExperimentOptParamValId getId() {
    return this.id;
  }

  public void setId(ExperimentOptParamValId id) {
    this.id = id;
  }

  public Experiment getExperiment() {
    return this.experiment;
  }

  public void setExperiment(Experiment experiment) {
    this.experiment = experiment;
  }

  public ExperimentOptParamDef getExperimentOptParamDef() {
    return this.experimentOptParamDef;
  }

  public void setExperimentOptParamDef(ExperimentOptParamDef experimentOptParamDef) {
    this.experimentOptParamDef = experimentOptParamDef;
  }

  public String getParamValue() {
    return this.paramValue;
  }

  public void setParamValue(String paramValue) {
    this.paramValue = paramValue;
  }
}


