package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExperimentOptParamDefGroupRelId generated by hbm2java
 */
@Embeddable
public class ExperimentOptParamDefGroupRelId implements java.io.Serializable {

	private int experimentOptParamDefId;
	private int researchGroupId;

	public ExperimentOptParamDefGroupRelId() {
	}

	public ExperimentOptParamDefGroupRelId(int experimentOptParamDefId,
			int researchGroupId) {
		this.experimentOptParamDefId = experimentOptParamDefId;
		this.researchGroupId = researchGroupId;
	}

	@Column(name = "EXPERIMENT_OPT_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)
	public int getExperimentOptParamDefId() {
		return this.experimentOptParamDefId;
	}

	public void setExperimentOptParamDefId(int experimentOptParamDefId) {
		this.experimentOptParamDefId = experimentOptParamDefId;
	}

	@Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)
	public int getResearchGroupId() {
		return this.researchGroupId;
	}

	public void setResearchGroupId(int researchGroupId) {
		this.researchGroupId = researchGroupId;
	}

}
