package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA


import javax.persistence.*;


/**
 * ExperimentOptParamVal generated by hbm2java
 */
@Entity
@javax.persistence.Table(name = "EXPERIMENT_OPT_PARAM_VAL")
public class ExperimentOptParamVal implements java.io.Serializable {
    @Id
    private ExperimentOptParamValId id;
    @ManyToOne
    @JoinColumn(name = "EXPERIMENT_ID")
    private Experiment experiment;
    @ManyToOne
    @JoinColumn(name = "EXPERIMENT_OPT_PARAM_DEF_ID")
    private ExperimentOptParamDef experimentOptParamDef;
    @Column(name = "PARAM_VALUE")
    private String paramValue;

    public ExperimentOptParamVal() {
    }

    public ExperimentOptParamVal(ExperimentOptParamValId id, Experiment experiment, ExperimentOptParamDef experimentOptParamDef, String paramValue) {
        this.id = id;
        this.experiment = experiment;
        this.experimentOptParamDef = experimentOptParamDef;
        this.paramValue = paramValue;
    }

    public ExperimentOptParamValId getId() {
        return this.id;
    }

    public void setId(ExperimentOptParamValId id) {
        this.id = id;
    }

    public Experiment getExperiment() {
        return this.experiment;
    }

    public void setExperiment(Experiment experiment) {
        this.experiment = experiment;
    }

    public ExperimentOptParamDef getExperimentOptParamDef() {
        return this.experimentOptParamDef;
    }

    public void setExperimentOptParamDef(ExperimentOptParamDef experimentOptParamDef) {
        this.experimentOptParamDef = experimentOptParamDef;
    }

    public String getParamValue() {
        return this.paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}


