package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FileMetadataParamDefGroupRelId generated by hbm2java
 */
@Embeddable
public class FileMetadataParamDefGroupRelId implements java.io.Serializable {

	private int fileMetadataParamDefId;
	private int researchGroupId;

	public FileMetadataParamDefGroupRelId() {
	}

	public FileMetadataParamDefGroupRelId(int fileMetadataParamDefId,
			int researchGroupId) {
		this.fileMetadataParamDefId = fileMetadataParamDefId;
		this.researchGroupId = researchGroupId;
	}

	@Column(name = "FILE_METADATA_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)
	public int getFileMetadataParamDefId() {
		return this.fileMetadataParamDefId;
	}

	public void setFileMetadataParamDefId(int fileMetadataParamDefId) {
		this.fileMetadataParamDefId = fileMetadataParamDefId;
	}

	@Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)
	public int getResearchGroupId() {
		return this.researchGroupId;
	}

	public void setResearchGroupId(int researchGroupId) {
		this.researchGroupId = researchGroupId;
	}

}
