/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   FileMetadataParamVal.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA


import javax.persistence.*;


/**
 * FileMetadataParamVal generated by hbm2java
 */
@Entity
@javax.persistence.Table(name = "FILE_METADATA_PARAM_VAL")
public class FileMetadataParamVal implements java.io.Serializable {
    //@SolrId TODO resolve the compound primary key issue
    @EmbeddedId
    private FileMetadataParamValId id;
    @ManyToOne
    @JoinColumn(name = "FILE_METADATA_PARAM_DEF_ID")
    private FileMetadataParamDef fileMetadataParamDef;
    @ManyToOne
    @JoinColumn(name = "DATA_FILE_ID")
    private DataFile dataFile;
    //@SolrField(name = IndexField.TEXT)
    @Column(name = "METADATA_VALUE")
    private String metadataValue;

    public FileMetadataParamVal() {
    }

    public FileMetadataParamVal(FileMetadataParamValId id, FileMetadataParamDef fileMetadataParamDef, DataFile dataFile, String metadataValue) {
        this.id = id;
        this.fileMetadataParamDef = fileMetadataParamDef;
        this.dataFile = dataFile;
        this.metadataValue = metadataValue;
    }

    public FileMetadataParamValId getId() {
        return this.id;
    }

    public void setId(FileMetadataParamValId id) {
        this.id = id;
    }

    public FileMetadataParamDef getFileMetadataParamDef() {
        return this.fileMetadataParamDef;
    }

    public void setFileMetadataParamDef(FileMetadataParamDef fileMetadataParamDef) {
        this.fileMetadataParamDef = fileMetadataParamDef;
    }

    public DataFile getDataFile() {
        return this.dataFile;
    }

    public void setDataFile(DataFile dataFile) {
        this.dataFile = dataFile;
    }

    public String getMetadataValue() {
        return this.metadataValue;
    }

    public void setMetadataValue(String metadataValue) {
        this.metadataValue = metadataValue;
    }
}


