/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   FileMetadataParamValId.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA


import javax.persistence.Embeddable;

/**
 * FileMetadataParamValId generated by hbm2java
 */
@Embeddable
public class FileMetadataParamValId  implements java.io.Serializable {


     private int fileMetadataParamDefId;
     private int dataFileId;

    public FileMetadataParamValId() {
    }

    public FileMetadataParamValId(int fileMetadataParamDefId, int dataFileId) {
       this.fileMetadataParamDefId = fileMetadataParamDefId;
       this.dataFileId = dataFileId;
    }
   
    public int getFileMetadataParamDefId() {
        return this.fileMetadataParamDefId;
    }
    
    public void setFileMetadataParamDefId(int fileMetadataParamDefId) {
        this.fileMetadataParamDefId = fileMetadataParamDefId;
    }
    public int getDataFileId() {
        return this.dataFileId;
    }
    
    public void setDataFileId(int dataFileId) {
        this.dataFileId = dataFileId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FileMetadataParamValId) ) return false;
		 FileMetadataParamValId castOther = ( FileMetadataParamValId ) other; 
         
		 return (this.getFileMetadataParamDefId()==castOther.getFileMetadataParamDefId())
 && (this.getDataFileId()==castOther.getDataFileId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFileMetadataParamDefId();
         result = 37 * result + this.getDataFileId();
         return result;
   }   


}


