package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * FileMetadataParamDef generated by hbm2java
 */
@Entity
@Table(name = "FILE_METADATA_PARAM_DEF")
public class FileMetadataParamDef implements java.io.Serializable {

	private int fileMetadataParamDefId;
	private String paramName;
	private String paramDataType;
	private int defaultNumber;
	private Set<FileMetadataParamVal> fileMetadataParamVals = new HashSet<FileMetadataParamVal>(
			0);
	private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);
	private Set<FileMetadataParamDef> fileMetadataParamDefGroupRels = new HashSet<FileMetadataParamDef>(
			0);

	public FileMetadataParamDef() {
	}

	public FileMetadataParamDef(String paramName, String paramDataType) {
		this.paramName = paramName;
		this.paramDataType = paramDataType;
	}

	public FileMetadataParamDef(String paramName, String paramDataType,
			int defaultNumber, Set<FileMetadataParamVal> fileMetadataParamVals,
			Set<ResearchGroup> researchGroups,
			Set<FileMetadataParamDef> fileMetadataParamDefGroupRels) {
		this.paramName = paramName;
		this.paramDataType = paramDataType;
		this.defaultNumber = defaultNumber;
		this.fileMetadataParamVals = fileMetadataParamVals;
		this.researchGroups = researchGroups;
		this.fileMetadataParamDefGroupRels = fileMetadataParamDefGroupRels;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "FILE_METADATA_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)
	public int getFileMetadataParamDefId() {
		return this.fileMetadataParamDefId;
	}

	public void setFileMetadataParamDefId(int fileMetadataParamDefId) {
		this.fileMetadataParamDefId = fileMetadataParamDefId;
	}

	@Column(name = "PARAM_NAME", nullable = false, length = 30)
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	@Column(name = "PARAM_DATA_TYPE", nullable = false, length = 20)
	public String getParamDataType() {
		return this.paramDataType;
	}

	public void setParamDataType(String paramDataType) {
		this.paramDataType = paramDataType;
	}

	@Column(name = "IS_DEFAULT", precision = 1, scale = 0)
	public int getDefaultNumber() {
		return this.defaultNumber;
	}

	public void setDefaultNumber(int defaultNumber) {
		this.defaultNumber = defaultNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fileMetadataParamDef")
	public Set<FileMetadataParamVal> getFileMetadataParamVals() {
		return this.fileMetadataParamVals;
	}

	public void setFileMetadataParamVals(
			Set<FileMetadataParamVal> fileMetadataParamVals) {
		this.fileMetadataParamVals = fileMetadataParamVals;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "FILE_METADATA_PARAM_GROUP_REL", joinColumns = { @JoinColumn(name = "FILE_METADATA_PARAM_DEF_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, updatable = false) })
	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}

}
