package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FileMetadataParamDefGroupRel generated by hbm2java
 */
@Entity
@Table(name = "FILE_METADATA_PARAM_GROUP_REL")
public class FileMetadataParamDefGroupRel implements java.io.Serializable {

	private FileMetadataParamDefGroupRelId id;
	private ResearchGroup researchGroup;
	private FileMetadataParamDef fileMetadataParamDef;

	public FileMetadataParamDefGroupRel() {
	}

	public FileMetadataParamDefGroupRel(FileMetadataParamDefGroupRelId id,
			ResearchGroup researchGroup,
			FileMetadataParamDef fileMetadataParamDef) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.fileMetadataParamDef = fileMetadataParamDef;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fileMetadataParamDefId", column = @Column(name = "FILE_METADATA_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "researchGroupId", column = @Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)) })
	public FileMetadataParamDefGroupRelId getId() {
		return this.id;
	}

	public void setId(FileMetadataParamDefGroupRelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, insertable = false, updatable = false)
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILE_METADATA_PARAM_DEF_ID", nullable = false, insertable = false, updatable = false)
	public FileMetadataParamDef getFileMetadataParamDef() {
		return this.fileMetadataParamDef;
	}

	public void setFileMetadataParamDef(
			FileMetadataParamDef fileMetadataParamDef) {
		this.fileMetadataParamDef = fileMetadataParamDef;
	}

}
