package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FileMetadataParamValId generated by hbm2java
 */
@Embeddable
public class FileMetadataParamValId implements java.io.Serializable {

	private int fileMetadataParamDefId;
	private int dataFileId;

	public FileMetadataParamValId() {
	}

	public FileMetadataParamValId(int fileMetadataParamDefId, int dataFileId) {
		this.fileMetadataParamDefId = fileMetadataParamDefId;
		this.dataFileId = dataFileId;
	}

	@Column(name = "FILE_METADATA_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)
	public int getFileMetadataParamDefId() {
		return this.fileMetadataParamDefId;
	}

	public void setFileMetadataParamDefId(int fileMetadataParamDefId) {
		this.fileMetadataParamDefId = fileMetadataParamDefId;
	}

	@Column(name = "DATA_FILE_ID", nullable = false, precision = 22, scale = 0)
	public int getDataFileId() {
		return this.dataFileId;
	}

	public void setDataFileId(int dataFileId) {
		this.dataFileId = dataFileId;
	}

}
