package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import org.hibernate.annotations.Entity;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Fields;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;

/**
 * FileMetadataParamVal generated by hbm2java
 */
//@Indexed
//@Entity
public class FileMetadataParamVal implements java.io.Serializable {
//@DocumentId
  private FileMetadataParamValId id;
  private FileMetadataParamDef fileMetadataParamDef;
  private DataFile dataFile;
//  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "METADATAVALUE")}) //use a different field name
  private String metadataValue;

  public FileMetadataParamVal() {
  }

  public FileMetadataParamVal(FileMetadataParamValId id, FileMetadataParamDef fileMetadataParamDef, DataFile dataFile, String metadataValue) {
    this.id = id;
    this.fileMetadataParamDef = fileMetadataParamDef;
    this.dataFile = dataFile;
    this.metadataValue = metadataValue;
  }

  public FileMetadataParamValId getId() {
    return this.id;
  }

  public void setId(FileMetadataParamValId id) {
    this.id = id;
  }

  public FileMetadataParamDef getFileMetadataParamDef() {
    return this.fileMetadataParamDef;
  }

  public void setFileMetadataParamDef(FileMetadataParamDef fileMetadataParamDef) {
    this.fileMetadataParamDef = fileMetadataParamDef;
  }

  public DataFile getDataFile() {
    return this.dataFile;
  }

  public void setDataFile(DataFile dataFile) {
    this.dataFile = dataFile;
  }

  public String getMetadataValue() {
    return this.metadataValue;
  }

  public void setMetadataValue(String metadataValue) {
    this.metadataValue = metadataValue;
  }
}


