package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * GroupPermissionRequest generated by hbm2java
 */
@Entity
@Table(name = "GROUP_PERMISSION_REQUEST")
public class GroupPermissionRequest implements java.io.Serializable {

	private int requestId;
	private Person person;
	private ResearchGroup researchGroup;
	private String requestedPermission;
	private boolean granted;

	public GroupPermissionRequest() {
	}

	public GroupPermissionRequest(Person person, ResearchGroup researchGroup,
			String requestedPermission) {
		this.person = person;
		this.researchGroup = researchGroup;
		this.requestedPermission = requestedPermission;
	}

	public GroupPermissionRequest(Person person, ResearchGroup researchGroup,
			String requestedPermission, boolean granted) {
		this.person = person;
		this.researchGroup = researchGroup;
		this.requestedPermission = requestedPermission;
		this.granted = granted;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "REQUEST_ID", nullable = false, precision = 22, scale = 0)
	public int getRequestId() {
		return this.requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PERSON_ID", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false)
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@Column(name = "REQUESTED_PERMISSION", nullable = false, length = 50)
	public String getRequestedPermission() {
		return this.requestedPermission;
	}

	public void setRequestedPermission(String requestedPermission) {
		this.requestedPermission = requestedPermission;
	}

	@Column(name = "GRANTED")
	public boolean isGranted() {
		return this.granted;
	}

	public void setGranted(boolean granted) {
		this.granted = granted;
	}

}
