package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HardwareGroupRelId generated by hbm2java
 */
@Embeddable
public class HardwareGroupRelId implements java.io.Serializable {

	private int hardwareId;
	private int researchGroupId;

	public HardwareGroupRelId() {
	}

	public HardwareGroupRelId(int hardwareId, int researchGroupId) {
		this.hardwareId = hardwareId;
		this.researchGroupId = researchGroupId;
	}

	@Column(name = "HARDWARE_ID", nullable = false, precision = 22, scale = 0)
	public int getHardwareId() {
		return this.hardwareId;
	}

	public void setHardwareId(int hardwareId) {
		this.hardwareId = hardwareId;
	}

	@Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)
	public int getResearchGroupId() {
		return this.researchGroupId;
	}

	public void setResearchGroupId(int researchGroupId) {
		this.researchGroupId = researchGroupId;
	}

}
