package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Entity;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Fields;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;

/**
 * Hardware generated by hbm2java
 */
@Entity
@Indexed
public class Hardware implements java.io.Serializable {
@DocumentId
  private int hardwareId;
  @Fields({
    @Field(index = Index.TOKENIZED), //same property indexed multiple times
    @Field(name = "title")}) //use a different field name
  private String title;
  @Fields({
    @Field(index = Index.TOKENIZED), //same property indexed multiple times
    @Field(name = "type")}) //use a different field name
  private String type;
  @Fields({
    @Field(index = Index.TOKENIZED), //same property indexed multiple times
    @Field(name = "description")}) //use a different field name
  private String description;
  private Set<Experiment> experiments = new HashSet<Experiment>(0);

  public Hardware() {
  }

  public Hardware(int hardwareId, String title, String type) {
    this.hardwareId = hardwareId;
    this.title = title;
    this.type = type;
  }

  public Hardware(int hardwareId, String title, String type, String description, Set<Experiment> experiments) {
    this.hardwareId = hardwareId;
    this.title = title;
    this.type = type;
    this.description = description;
    this.experiments = experiments;
  }

  public int getHardwareId() {
    return this.hardwareId;
  }

  public void setHardwareId(int hardwareId) {
    this.hardwareId = hardwareId;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Set<Experiment> getExperiments() {
    return this.experiments;
  }

  public void setExperiments(Set<Experiment> experiments) {
    this.experiments = experiments;
  }
}


