package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import org.hibernate.annotations.Entity;
import org.hibernate.search.annotations.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Hardware generated by hbm2java
 */
@Entity
@Indexed
public class Hardware implements Serializable {
    @DocumentId
    private int hardwareId;
    @Fields({
            @Field(index = Index.TOKENIZED), //same property indexed multiple times
            @Field(name = "title")}) //use a different field name
    private String title;
    @Fields({
            @Field(index = Index.TOKENIZED), //same property indexed multiple times
            @Field(name = "type")}) //use a different field name
    private String type;
    @Fields({
            @Field(index = Index.TOKENIZED), //same property indexed multiple times
            @Field(name = "description")}) //use a different field name
    private String description;
    private Set<Experiment> experiments = new HashSet<Experiment>(0);
    private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);
    private Set<HardwareGroupRel> hardwareGroupRels = new HashSet<HardwareGroupRel>(0);
    private long scn;
    private int defaultNumber;

    public Hardware() {
    }

    public Hardware(int hardwareId, String title, String type) {
        this.hardwareId = hardwareId;
        this.title = title;
        this.type = type;
    }

    public Hardware(int hardwareId, String title, String type, String description, Set<Experiment> experiments) {
        this.hardwareId = hardwareId;
        this.title = title;
        this.type = type;
        this.description = description;
        this.experiments = experiments;
    }

    public Hardware(int hardwareId, String title, String type, String description, int defaultNumber, Set<Experiment> experiments, Set<ResearchGroup> researchGroups) {
        this.hardwareId = hardwareId;
        this.title = title;
        this.type = type;
        this.description = description;
        this.defaultNumber = defaultNumber;
        this.experiments = experiments;
        this.researchGroups = researchGroups;
    }

    public int getHardwareId() {
        return this.hardwareId;
    }

    public void setHardwareId(int hardwareId) {
        this.hardwareId = hardwareId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }

    public long getScn() {
        return scn;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDefaultNumber(int defaultNumber){
        this.defaultNumber = defaultNumber;
    }

    public int getDefaultNumber() {
        return defaultNumber;
    }

    public Set<Experiment> getExperiments() {
        return this.experiments;
    }

    public void setExperiments(Set<Experiment> experiments) {
        this.experiments = experiments;
    }

    public Set<ResearchGroup> getResearchGroups() {
        return researchGroups;
    }

    public Set<HardwareGroupRel> getHardwareGroupRels() {
        return hardwareGroupRels;
    }

    public void setHardwareGroupRels(Set<HardwareGroupRel> hardwareGroupRels) {
        this.hardwareGroupRels = hardwareGroupRels;
    }

    public void setResearchGroups(Set<ResearchGroup> researchGroups) {
        this.researchGroups = researchGroups;
    }

}


