package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Entity;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Fields;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;

/**
 * HearingImpairment generated by hbm2java
 */
@Entity
@Indexed
public class HearingImpairment implements java.io.Serializable {
@DocumentId
  private int hearingImpairmentId;
  @Fields({
    @Field(index = Index.TOKENIZED), //same property indexed multiple times
    @Field(name = "description")}) //use a different field name
    private String description;
    private Set<Person> persons = new HashSet<Person>(0);
    private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);
    private Set<HearingImpairmentGroupRel> hearingImpairmentGroupRels = new HashSet<HearingImpairmentGroupRel>(0);
    private int defaultNumber;

  public HearingImpairment() {
  }

  public HearingImpairment(int hearingImpairmentId, String description) {
    this.hearingImpairmentId = hearingImpairmentId;
    this.description = description;
  }

  public HearingImpairment(int hearingImpairmentId, String description, Set<Person> persons) {
    this.hearingImpairmentId = hearingImpairmentId;
    this.description = description;
    this.persons = persons;
  }

  public int getHearingImpairmentId() {
    return this.hearingImpairmentId;
  }

  public void setHearingImpairmentId(int hearingImpairmentId) {
    this.hearingImpairmentId = hearingImpairmentId;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Set<Person> getPersons() {
    return this.persons;
  }

  public void setPersons(Set<Person> persons) {
    this.persons = persons;
  }

    public Set<ResearchGroup> getResearchGroups() {
        return researchGroups;
    }

    public void setResearchGroups(Set<ResearchGroup> researchGroups) {
        this.researchGroups = researchGroups;
    }

    public Set<HearingImpairmentGroupRel> getHearingImpairmentGroupRels() {
        return hearingImpairmentGroupRels;
    }

    public void setHearingImpairmentGroupRels(Set<HearingImpairmentGroupRel> hearingImpairmentGroupRels) {
        this.hearingImpairmentGroupRels = hearingImpairmentGroupRels;
    }

    public int getDefaultNumber() {
        return defaultNumber;
    }

    public void setDefaultNumber(int defaultNumber) {
        this.defaultNumber = defaultNumber;
    }
}


