package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "HISTORY")
public class History implements java.io.Serializable {

	private int historyId;
	private Experiment experiment;
	private Scenario scenario;
	private DataFile dataFile;
	private Person person;
	private Timestamp dateOfDownload;

	public History() {
	}

	public History(Person person, Timestamp dateOfDownload) {
		this.person = person;
		this.dateOfDownload = dateOfDownload;
	}

	public History(Experiment experiment, Scenario scenario, DataFile dataFile,
			Person person, Timestamp dateOfDownload) {
		this.experiment = experiment;
		this.scenario = scenario;
		this.dataFile = dataFile;
		this.person = person;
		this.dateOfDownload = dateOfDownload;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "HISTORY_ID", nullable = false, precision = 22, scale = 0)
	public int getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(int historyId) {
		this.historyId = historyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPERIMENT_ID")
	public Experiment getExperiment() {
		return this.experiment;
	}

	public void setExperiment(Experiment experiment) {
		this.experiment = experiment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCENARIO_ID")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DATA_FILE_ID")
	public DataFile getDataFile() {
		return this.dataFile;
	}

	public void setDataFile(DataFile dataFile) {
		this.dataFile = dataFile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_ID", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "DATE_OF_DOWNLOAD", nullable = false, length = 7)
	public Timestamp getDateOfDownload() {
		return this.dateOfDownload;
	}

	public void setDateOfDownload(Timestamp dateOfDownload) {
		this.dateOfDownload = dateOfDownload;
	}

}
