/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   Keywords.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * Keywords generated by hbm2java
 */
@Entity
@Table(name = "KEYWORDS")
public class Keywords implements java.io.Serializable {

	private int keywordsId;
	private ResearchGroup researchGroup;
    private ExperimentPackage experimentPackage;
	private String keywordsText;

	public Keywords() {
	}

	public Keywords(ResearchGroup researchGroup, String keywordsText) {
		this.researchGroup = researchGroup;
		this.keywordsText = keywordsText;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "KEYWORDS_ID", nullable = false, precision = 22, scale = 0)
	public int getKeywordsId() {
		return this.keywordsId;
	}

	public void setKeywordsId(int keywordsId) {
		this.keywordsId = keywordsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_GROUP_ID")
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@Column(name = "KEYWORDS_TEXT")
	public String getKeywordsText() {
		return this.keywordsText;
	}

	public void setKeywordsText(String keywordsText) {
		this.keywordsText = keywordsText;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EXPERIMENT_PACKAGE_ID")
    public ExperimentPackage getExperimentPackage() {
        return experimentPackage;
    }

    public void setExperimentPackage(ExperimentPackage experimentPackage) {
        this.experimentPackage = experimentPackage;
    }
}
