package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Keywords generated by hbm2java
 */
@Entity
@Table(name = "KEYWORDS")
public class Keywords implements java.io.Serializable {

	private int keywordsId;
	private ResearchGroup researchGroup;
	private String keywordsText;

	public Keywords() {
	}

	public Keywords(ResearchGroup researchGroup, String keywordsText) {
		this.researchGroup = researchGroup;
		this.keywordsText = keywordsText;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "KEYWORDS_ID", nullable = false, precision = 22, scale = 0)
	public int getKeywordsId() {
		return this.keywordsId;
	}

	public void setKeywordsId(int keywordsId) {
		this.keywordsId = keywordsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_GROUP_ID")
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@Column(name = "KEYWORDS_TEXT")
	public String getKeywordsText() {
		return this.keywordsText;
	}

	public void setKeywordsText(String keywordsText) {
		this.keywordsText = keywordsText;
	}

}
