package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

/**
 * PersonOptParamVal generated by hbm2java
 */
//@Entity
//@Indexed
public class PersonOptParamVal implements java.io.Serializable {
//@DocumentId
  private PersonOptParamValId id;
  private PersonOptParamDef personOptParamDef;
  private Person person;
//  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "PERSONPARAMVALUE")}) //use a different field name
  private String paramValue;

  public PersonOptParamVal() {
  }

  public PersonOptParamVal(PersonOptParamValId id, PersonOptParamDef personOptParamDef, Person person, String paramValue) {
    this.id = id;
    this.personOptParamDef = personOptParamDef;
    this.person = person;
    this.paramValue = paramValue;
  }

  public PersonOptParamValId getId() {
    return this.id;
  }

  public void setId(PersonOptParamValId id) {
    this.id = id;
  }

  public PersonOptParamDef getPersonOptParamDef() {
    return this.personOptParamDef;
  }

  public void setPersonOptParamDef(PersonOptParamDef personOptParamDef) {
    this.personOptParamDef = personOptParamDef;
  }

  public Person getPerson() {
    return this.person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public String getParamValue() {
    return this.paramValue;
  }

  public void setParamValue(String paramValue) {
    this.paramValue = paramValue;
  }
}


