package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonOptParamDefGroupRelId generated by hbm2java
 */
@Embeddable
public class PersonOptParamDefGroupRelId implements java.io.Serializable {

	private int personOptParamDefId;
	private int researchGroupId;

	public PersonOptParamDefGroupRelId() {
	}

	public PersonOptParamDefGroupRelId(int personOptParamDefId,
			int researchGroupId) {
		this.personOptParamDefId = personOptParamDefId;
		this.researchGroupId = researchGroupId;
	}

	@Column(name = "PERSON_OPT_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)
	public int getPersonOptParamDefId() {
		return this.personOptParamDefId;
	}

	public void setPersonOptParamDefId(int personOptParamDefId) {
		this.personOptParamDefId = personOptParamDefId;
	}

	@Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)
	public int getResearchGroupId() {
		return this.researchGroupId;
	}

	public void setResearchGroupId(int researchGroupId) {
		this.researchGroupId = researchGroupId;
	}

}
