/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   PersonOptParamValId.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA


import javax.persistence.Embeddable;

/**
 * PersonOptParamValId generated by hbm2java
 */
@Embeddable
public class PersonOptParamValId  implements java.io.Serializable {


     private int personId;
     private int personAdditionalParamId;

    public PersonOptParamValId() {
    }

    public PersonOptParamValId(int personId, int personAdditionalParamId) {
       this.personId = personId;
       this.personAdditionalParamId = personAdditionalParamId;
    }
   
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }
    public int getPersonAdditionalParamId() {
        return this.personAdditionalParamId;
    }
    
    public void setPersonAdditionalParamId(int personAdditionalParamId) {
        this.personAdditionalParamId = personAdditionalParamId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonOptParamValId) ) return false;
		 PersonOptParamValId castOther = ( PersonOptParamValId ) other; 
         
		 return (this.getPersonId()==castOther.getPersonId())
 && (this.getPersonAdditionalParamId()==castOther.getPersonAdditionalParamId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPersonId();
         result = 37 * result + this.getPersonAdditionalParamId();
         return result;
   }   


}


