package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * PersonOptParamDef generated by hbm2java
 */
//@Entity
//@Indexed
public class PersonOptParamDef implements java.io.Serializable {
//@DocumentId
  private int personOptParamDefId;
//  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "PERSONPARAMNAME")}) //use a different field name
  private String paramName;
//  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "PARAMDATATYPE")}) //use a different field name
  private String paramDataType;
  private Set<PersonOptParamVal> personOptParamVals = new HashSet<PersonOptParamVal>(0);
  private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);
  private Set<PersonOptParamDefGroupRel> personOptParamDefGroupRels = new HashSet<PersonOptParamDefGroupRel>(0);
  private int defaultNumber; 
    
  public PersonOptParamDef() {
  }

  public PersonOptParamDef(int personOptParamDefId, String paramName, String paramDataType) {
    this.personOptParamDefId = personOptParamDefId;
    this.paramName = paramName;
    this.paramDataType = paramDataType;
  }

  public PersonOptParamDef(int personOptParamDefId, String paramName, String paramDataType, Set<PersonOptParamVal> personOptParamVals) {
    this.personOptParamDefId = personOptParamDefId;
    this.paramName = paramName;
    this.paramDataType = paramDataType;
    this.personOptParamVals = personOptParamVals;
  }

  public int getPersonOptParamDefId() {
    return this.personOptParamDefId;
  }

  public void setPersonOptParamDefId(int personOptParamDefId) {
    this.personOptParamDefId = personOptParamDefId;
  }

  public String getParamName() {
    return this.paramName;
  }

  public void setParamName(String paramName) {
    this.paramName = paramName;
  }

  public String getParamDataType() {
    return this.paramDataType;
  }

  public void setParamDataType(String paramDataType) {
    this.paramDataType = paramDataType;
  }

  public Set<PersonOptParamVal> getPersonOptParamVals() {
    return this.personOptParamVals;
  }

  public void setPersonOptParamVals(Set<PersonOptParamVal> personOptParamVals) {
    this.personOptParamVals = personOptParamVals;
  }

    public Set<ResearchGroup> getResearchGroups() {
        return researchGroups;
    }

    public void setResearchGroups(Set<ResearchGroup> researchGroups) {
        this.researchGroups = researchGroups;
    }

    public Set<PersonOptParamDefGroupRel> getPersonOptParamDefGroupRels() {
        return personOptParamDefGroupRels;
    }

    public void setPersonOptParamDefGroupRels(Set<PersonOptParamDefGroupRel> personOptParamDefGroupRels) {
        this.personOptParamDefGroupRels = personOptParamDefGroupRels;
    }

    public int getDefaultNumber() {
        return defaultNumber;
    }

    public void setDefaultNumber(int defaultNumber) {
        this.defaultNumber = defaultNumber;
    }
}
