package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonOptParamValId generated by hbm2java
 */
@Embeddable
public class PersonOptParamValId implements java.io.Serializable {

	private int personId;
	private int personAdditionalParamId;

	public PersonOptParamValId() {
	}

	public PersonOptParamValId(int personId, int personAdditionalParamId) {
		this.personId = personId;
		this.personAdditionalParamId = personAdditionalParamId;
	}

	@Column(name = "PERSON_ID", nullable = false, precision = 22, scale = 0)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	@Column(name = "PERSON_OPT_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)
	public int getPersonAdditionalParamId() {
		return this.personAdditionalParamId;
	}

	public void setPersonAdditionalParamId(int personAdditionalParamId) {
		this.personAdditionalParamId = personAdditionalParamId;
	}

}
