package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonOptParamDefGroupRel generated by hbm2java
 */
@Entity
@Table(name = "PERSON_OPT_PARAM_GROUP_REL")
public class PersonOptParamDefGroupRel implements java.io.Serializable {

	private PersonOptParamDefGroupRelId id;
	private ResearchGroup researchGroup;
	private PersonOptParamDef personOptParamDef;

	public PersonOptParamDefGroupRel() {
	}

	public PersonOptParamDefGroupRel(PersonOptParamDefGroupRelId id,
			ResearchGroup researchGroup, PersonOptParamDef personOptParamDef) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.personOptParamDef = personOptParamDef;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "personOptParamDefId", column = @Column(name = "PERSON_OPT_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "researchGroupId", column = @Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)) })
	public PersonOptParamDefGroupRelId getId() {
		return this.id;
	}

	public void setId(PersonOptParamDefGroupRelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, insertable = false, updatable = false)
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_OPT_PARAM_DEF_ID", nullable = false, insertable = false, updatable = false)
	public PersonOptParamDef getPersonOptParamDef() {
		return this.personOptParamDef;
	}

	public void setPersonOptParamDef(PersonOptParamDef personOptParamDef) {
		this.personOptParamDef = personOptParamDef;
	}

}
