package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonOptParamVal generated by hbm2java
 */
@Entity
@Table(name = "PERSON_OPT_PARAM_VAL")
public class PersonOptParamVal implements java.io.Serializable {

	private PersonOptParamValId id;
	private PersonOptParamDef personOptParamDef;
	private Person person;
	private String paramValue;

	public PersonOptParamVal() {
	}

	public PersonOptParamVal(PersonOptParamValId id,
			PersonOptParamDef personOptParamDef, Person person,
			String paramValue) {
		this.id = id;
		this.personOptParamDef = personOptParamDef;
		this.person = person;
		this.paramValue = paramValue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "personId", column = @Column(name = "PERSON_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "personAdditionalParamId", column = @Column(name = "PERSON_OPT_PARAM_DEF_ID", nullable = false, precision = 22, scale = 0)) })
	public PersonOptParamValId getId() {
		return this.id;
	}

	public void setId(PersonOptParamValId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_OPT_PARAM_DEF_ID", nullable = false, insertable = false, updatable = false)
	public PersonOptParamDef getPersonOptParamDef() {
		return this.personOptParamDef;
	}

	public void setPersonOptParamDef(PersonOptParamDef personOptParamDef) {
		this.personOptParamDef = personOptParamDef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_ID", nullable = false, insertable = false, updatable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "PARAM_VALUE", nullable = false, length = 30)
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

}
