package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResearchGroupMembershipId generated by hbm2java
 */
@Embeddable
public class ResearchGroupMembershipId implements java.io.Serializable {

	private int personId;
	private int researchGroupId;

	public ResearchGroupMembershipId() {
	}

	public ResearchGroupMembershipId(int personId, int researchGroupId) {
		this.personId = personId;
		this.researchGroupId = researchGroupId;
	}

	@Column(name = "PERSON_ID", nullable = false, precision = 22, scale = 0)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	@Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)
	public int getResearchGroupId() {
		return this.researchGroupId;
	}

	public void setResearchGroupId(int researchGroupId) {
		this.researchGroupId = researchGroupId;
	}

}
