package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ResearchGroup generated by hbm2java
 */
//@Entity
//@Indexed
public class ResearchGroup implements Serializable {
    //@DocumentId
    private int researchGroupId;
    private Person person;
    //  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "RESEARCHGROUPTITLE")}) //use a different field name
    private String title;
    //  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "RESEARCHGROUPDESCRIPTION")}) //use a different field name
    private String description;
    private Set<ResearchGroupMembership> researchGroupMemberships = new HashSet<ResearchGroupMembership>(0);
    private Set<Scenario> scenarios = new HashSet<Scenario>(0);
    private Set<Experiment> experiments = new HashSet<Experiment>(0);
    private Set<Person> usersWithThisAsDefault = new HashSet<Person>(0);
    private Set<GroupPermissionRequest> requests = new HashSet<GroupPermissionRequest>(0);
    private Set<Person> articlesSubscribers = new HashSet<Person>(0);
    private Set<HardwareGroupRel> hardwareGroupRels = new HashSet<HardwareGroupRel>(0);
    private Set<WeatherGroupRel> weatherGroupRels = new HashSet<WeatherGroupRel>(0);
    private Set<Hardware> hardwares = new HashSet<Hardware>(0);
    private Set<Weather> weathers = new HashSet<Weather>(0);
    private Set<FileMetadataParamDef> fileMetadataParamDefs = new HashSet<FileMetadataParamDef>(0);
    private Set<FileMetadataParamDefGroupRel> fileMetadataParamDefGroupRels = new HashSet<FileMetadataParamDefGroupRel>(0);
    private Set<PersonOptParamDef> personOptParamDefs = new HashSet<PersonOptParamDef>(0);
    private Set<PersonOptParamDefGroupRel> personOptParamDefGroupRels = new HashSet<PersonOptParamDefGroupRel>(0);
    private Set<ExperimentOptParamDef> experimentOptParamDefs = new HashSet<ExperimentOptParamDef>(0);
    private Set<ExperimentOptParamDefGroupRel> experimentOptParamDefGroupRels = new HashSet<ExperimentOptParamDefGroupRel>(0);

    private long scn;

    public ResearchGroup() {
    }

    public ResearchGroup(int researchGroupId, Person person, String title, String description) {
        this.researchGroupId = researchGroupId;
        this.person = person;
        this.title = title;
        this.description = description;
    }

    public ResearchGroup(int researchGroupId, Person person, String title, String description, Set<ResearchGroupMembership> researchGroupMemberships, Set<Scenario> scenarios, Set<Experiment> experiments, Set<Hardware> hardwares) {
        this.researchGroupId = researchGroupId;
        this.person = person;
        this.title = title;
        this.description = description;
        this.researchGroupMemberships = researchGroupMemberships;
        this.scenarios = scenarios;
        this.experiments = experiments;
        this.hardwares = hardwares;
    }

    public int getResearchGroupId() {
        return this.researchGroupId;
    }

    public void setResearchGroupId(int researchGroupId) {
        this.researchGroupId = researchGroupId;
    }

    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public long getScn() {
        return scn;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<ResearchGroupMembership> getResearchGroupMemberships() {
        return this.researchGroupMemberships;
    }

    public void setResearchGroupMemberships(Set<ResearchGroupMembership> researchGroupMemberships) {
        this.researchGroupMemberships = researchGroupMemberships;
    }

    public Set<Scenario> getScenarios() {
        return this.scenarios;
    }

    public void setScenarios(Set<Scenario> scenarios) {
        this.scenarios = scenarios;
    }

    public Set<Experiment> getExperiments() {
        return this.experiments;
    }

    public void setExperiments(Set<Experiment> experiments) {
        this.experiments = experiments;
    }

    public Set<Person> getUsersWithThisAsDefault() {
        return usersWithThisAsDefault;
    }

    public void setUsersWithThisAsDefault(Set<Person> usersWithThisAsDefault) {
        this.usersWithThisAsDefault = usersWithThisAsDefault;
    }

    public Set<GroupPermissionRequest> getRequests() {
        return requests;
    }

    public void setRequests(Set<GroupPermissionRequest> requests) {
        this.requests = requests;
    }

    public Set<Person> getArticlesSubscribers() {
        return articlesSubscribers;
    }

    public Set<HardwareGroupRel> getHardwareGroupRels() {
        return hardwareGroupRels;
    }

    public void setHardwareGroupRels(Set<HardwareGroupRel> hardwareGroupRels) {
        this.hardwareGroupRels = hardwareGroupRels;
    }

    public Set<WeatherGroupRel> getWeatherGroupRels() {
        return weatherGroupRels;
    }

    public void setWeatherGroupRels(Set<WeatherGroupRel> weatherGroupRels) {
        this.weatherGroupRels = weatherGroupRels;
    }

    public void setArticlesSubscribers(Set<Person> articlesSubscribers) {
        this.articlesSubscribers = articlesSubscribers;
    }

    public Set<Hardware> getHardwares() {
        return this.hardwares;
    }

    public void setHardwares(Set<Hardware> hardwares) {
        this.hardwares = hardwares;
    }

    public Set<Weather> getWeathers() {
        return weathers;
    }

    public void setWeathers(Set<Weather> weathers) {
        this.weathers = weathers;
    }


    public Set<FileMetadataParamDef> getFileMetadataParamDefs() {
        return fileMetadataParamDefs;
    }

    public void setFileMetadataParamDefs(Set<FileMetadataParamDef> fileMetadataParamDefs) {
        this.fileMetadataParamDefs = fileMetadataParamDefs;
    }

    public Set<FileMetadataParamDefGroupRel> getFileMetadataParamDefGroupRels() {
        return fileMetadataParamDefGroupRels;
    }

    public void setFileMetadataParamDefGroupRels(Set<FileMetadataParamDefGroupRel> fileMetadataParamDefGroupRels) {
        this.fileMetadataParamDefGroupRels = fileMetadataParamDefGroupRels;
    }

    public Set<PersonOptParamDef> getPersonOptParamDefs() {
        return personOptParamDefs;
    }

    public void setPersonOptParamDefs(Set<PersonOptParamDef> personOptParamDefs) {
        this.personOptParamDefs = personOptParamDefs;
    }

    public Set<PersonOptParamDefGroupRel> getPersonOptParamDefGroupRels() {
        return personOptParamDefGroupRels;
    }

    public void setPersonOptParamDefGroupRels(Set<PersonOptParamDefGroupRel> personOptParamDefGroupRels) {
        this.personOptParamDefGroupRels = personOptParamDefGroupRels;
    }

    public Set<ExperimentOptParamDef> getExperimentOptParamDefs() {
        return experimentOptParamDefs;
    }

    public void setExperimentOptParamDefs(Set<ExperimentOptParamDef> experimentOptParamDefs) {
        this.experimentOptParamDefs = experimentOptParamDefs;
    }

    public Set<ExperimentOptParamDefGroupRel> getExperimentOptParamDefGroupRels() {
        return experimentOptParamDefGroupRels;
    }

    public void setExperimentOptParamDefGroupRels(Set<ExperimentOptParamDefGroupRel> experimentOptParamDefGroupRels) {
        this.experimentOptParamDefGroupRels = experimentOptParamDefGroupRels;
    }
}


