package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 15.1.2011 15:15:26 by Hibernate Tools 3.2.1.GA


import javax.persistence.*;
import java.sql.Timestamp;

/**
 * Reservation generated by hbm2java
 */
@Entity
@javax.persistence.Table(name = "RESERVATION")
public class Reservation implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "RESERVATION_ID")
    private int reservationId;
    @ManyToOne
    @JoinColumn(name = "RESEARCH_GROUP_ID")
    private ResearchGroup researchGroup;
    @ManyToOne
    @JoinColumn(name = "PERSON_ID")
    private Person person;
    @Column(name = "CREATION_TIME")
    private Timestamp creationTime;
    @Column(name = "START_TIME")
    private Timestamp startTime;
    @Column(name = "END_TIME")
    private Timestamp endTime;

    public Reservation() {
    }


    public Reservation(int reservationId) {
        this.reservationId = reservationId;
    }

    public Reservation(int reservationId, ResearchGroup researchGroup, Person person, Timestamp creationTime, Timestamp startTime, Timestamp endTime) {
        this.reservationId = reservationId;
        this.researchGroup = researchGroup;
        this.person = person;
        this.creationTime = creationTime;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public int getReservationId() {
        return this.reservationId;
    }

    public void setReservationId(int reservationId) {
        this.reservationId = reservationId;
    }

    public ResearchGroup getResearchGroup() {
        return this.researchGroup;
    }

    public void setResearchGroup(ResearchGroup researchGroup) {
        this.researchGroup = researchGroup;
    }

    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public Timestamp getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Timestamp creationTime) {
        this.creationTime = creationTime;
    }

    public Timestamp getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    public Timestamp getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }


}


