/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   ResearchGroupMembership.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import javax.persistence.*;

/**
 * ResearchGroupMembership generated by hbm2java
 */
@Entity
@javax.persistence.Table(name="RESEARCH_GROUP_MEMBERSHIP")
public class ResearchGroupMembership implements java.io.Serializable {
    @EmbeddedId
  private ResearchGroupMembershipId id;
    @ManyToOne
    @JoinColumn(name = "RESEARCH_GROUP_ID")
  private ResearchGroup researchGroup;
    @ManyToOne
    @JoinColumn(name = "PERSON_ID")
  private Person person;
    @Column(name = "AUTHORITY")
  private String authority;

  public ResearchGroupMembership() {
  }

  public ResearchGroupMembership(ResearchGroupMembershipId id, ResearchGroup researchGroup, Person person, String authority) {
    this.id = id;
    this.researchGroup = researchGroup;
    this.person = person;
    this.authority = authority;
  }

  public ResearchGroupMembershipId getId() {
    return this.id;
  }

  public void setId(ResearchGroupMembershipId id) {
    this.id = id;
  }

  public ResearchGroup getResearchGroup() {
    return this.researchGroup;
  }

  public void setResearchGroup(ResearchGroup researchGroup) {
    this.researchGroup = researchGroup;
  }

  public Person getPerson() {
    return this.person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public String getAuthority() {
    return this.authority;
  }

  public void setAuthority(String authority) {
    this.authority = authority;
  }
}


