package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResearchGroupMembership generated by hbm2java
 */
@Entity
@Table(name = "RESEARCH_GROUP_MEMBERSHIP")
public class ResearchGroupMembership implements java.io.Serializable {

	private ResearchGroupMembershipId id;
	private ResearchGroup researchGroup;
	private Person person;
	private String authority;

	public ResearchGroupMembership() {
	}

	public ResearchGroupMembership(ResearchGroupMembershipId id,
			ResearchGroup researchGroup, Person person, String authority) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.person = person;
		this.authority = authority;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "personId", column = @Column(name = "PERSON_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "researchGroupId", column = @Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)) })
	public ResearchGroupMembershipId getId() {
		return this.id;
	}

	public void setId(ResearchGroupMembershipId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, insertable = false, updatable = false)
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_ID", nullable = false, insertable = false, updatable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "AUTHORITY", nullable = false, length = 30)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
