/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   ScenarioSchemas.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/


//@TODO: this should be removed as its not used. Im not removing it now as it has too many dependencies.. @bydga
package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * ScenarioSchemas generated by hbm2java
 */
@Entity
@Table(name = "SCENARIO_SCHEMA")
public class ScenarioSchemas implements java.io.Serializable {

	private int schemaId;
	private String schemaName;
	private Clob sql;
	private Clob hbmXml;
	private Clob pojo;
	private String bean;
	private String description;
	private char approved;

	public ScenarioSchemas() {
	}

	public ScenarioSchemas(String schemaName, Clob sql, Clob hbmXml, Clob pojo,
			String bean, String description, char approved) {
		this.schemaName = schemaName;
		this.sql = sql;
		this.hbmXml = hbmXml;
		this.pojo = pojo;
		this.bean = bean;
		this.description = description;
		this.approved = approved;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "SCHEMA_ID", nullable = false, precision = 22, scale = 0)
	public int getSchemaId() {
		return this.schemaId;
	}

	public void setSchemaId(int schemaId) {
		this.schemaId = schemaId;
	}

	@Column(name = "SCHEMA_NAME")
	public String getSchemaName() {
		return this.schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	@Column(name = "SQL")
	public Clob getSql() {
		return this.sql;
	}

	public void setSql(Clob sql) {
		this.sql = sql;
	}

	@Column(name = "HBM_XML")
	public Clob getHbmXml() {
		return this.hbmXml;
	}

	public void setHbmXml(Clob hbmXml) {
		this.hbmXml = hbmXml;
	}

	@Column(name = "POJO")
	public Clob getPojo() {
		return this.pojo;
	}

	public void setPojo(Clob pojo) {
		this.pojo = pojo;
	}

	@Column(name = "BEAN")
	public String getBean() {
		return this.bean;
	}

	public void setBean(String bean) {
		this.bean = bean;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "APPROVED")
	public char getApproved() {
		return this.approved;
	}

	public void setApproved(char approved) {
		this.approved = approved;
	}

}
