//@TODO: this should be removed as its not used. Im not removing it now as it has too many dependencies.. @bydga
package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * ScenarioType generated by hbm2java
 */
@Entity
@Table(name = "SCENARIO_TYPE_PARENT")
public class ScenarioType<T> implements  java.io.Serializable {

	private int scenarioId;
	private Scenario scenario;

	public ScenarioType() {
	}

	public ScenarioType(Scenario scenario) {
		this.scenario = scenario;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "SCENARIO_ID", nullable = false, precision = 22, scale = 0)
	public int getScenarioId() {
		return this.scenarioId;
	}

	public void setScenarioId(int scenarioId) {
		this.scenarioId = scenarioId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}
	
}
