package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * ServiceResult generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_RESULT")
public class ServiceResult implements java.io.Serializable {

	private int serviceResultId;
	private Person owner;
	private byte[] figure;
	private String filename;
	private String title;
	private String status;

	public ServiceResult() {
	}

	public ServiceResult(Person owner, String title, String status) {
		this.owner = owner;
		this.title = title;
		this.status = status;
	}

	public ServiceResult(Person owner, byte[] figure, String filename,
			String title, String status) {
		this.owner = owner;
		this.figure = figure;
		this.filename = filename;
		this.title = title;
		this.status = status;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "RESULT_ID", nullable = false, precision = 22, scale = 0)
	public int getServiceResultId() {
		return this.serviceResultId;
	}

	public void setServiceResultId(int serviceResultId) {
		this.serviceResultId = serviceResultId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_ID", nullable = false)
	public Person getOwner() {
		return this.owner;
	}

	public void setOwner(Person owner) {
		this.owner = owner;
	}

	@Column(name = "FIGURE")
	public byte[] getFigure() {
		return this.figure;
	}

	public void setFigure(byte[] figure) {
		this.figure = figure;
	}

	@Column(name = "FILENAME", length = 80)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "TITLE", nullable = false, length = 80)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
