/*******************************************************************************
 * This file is part of the EEG-database project
 * 
 *   ==========================================
 *  
 *   Copyright (C) 2013 by University of West Bohemia (http://www.zcu.cz/en/)
 *  
 *  ***********************************************************************************************************************
 *  
 *   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 *   the License. You may obtain a copy of the License at
 *  
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 *   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 *  
 *  ***********************************************************************************************************************
 *  
 *   Stimulus.java, 2013/10/02 00:01 Jakub Rinkes
 ******************************************************************************/
package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1
import cz.zcu.kiv.eegdatabase.wui.ui.experiments.converters.IAutoCompletable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.GenericGenerator;

/**
 * Stimulus generated by hbm2java
 */
@Entity
@Table(name = "STIMULUS")
public class Stimulus implements java.io.Serializable, IAutoCompletable {

	private int stimulusId;
	private String description;
	private Set<StimulusRel> stimulusRels = new HashSet<StimulusRel>(0);

	public Stimulus() {
	}

	public Stimulus(String description, Set<StimulusRel> stimulusRels) {
		this.description = description;
		this.stimulusRels = stimulusRels;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "STIMULUS_ID", nullable = false, precision = 22, scale = 0)
	public int getStimulusId() {
		return this.stimulusId;
	}

	public void setStimulusId(int stimulusId) {
		this.stimulusId = stimulusId;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stimulus")
	public Set<StimulusRel> getStimulusRels() {
		return this.stimulusRels;
	}

	public void setStimulusRels(Set<StimulusRel> stimulusRels) {
		this.stimulusRels = stimulusRels;
	}

	@Override
	@Transient
	public String getAutoCompleteData() {
		return description;
	}
}
