package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StimulusRelId generated by hbm2java
 */
@Embeddable
public class StimulusRelId implements java.io.Serializable {

	private int scenarioId;
	private int stimulusId;

	public StimulusRelId() {
	}

	public StimulusRelId(int scenarioId, int stimulusId) {
		this.scenarioId = scenarioId;
		this.stimulusId = stimulusId;
	}

	@Column(name = "SCENARIO_ID", nullable = false, precision = 22, scale = 0)
	public int getScenarioId() {
		return this.scenarioId;
	}

	public void setScenarioId(int scenarioId) {
		this.scenarioId = scenarioId;
	}

	@Column(name = "STIMULUS_ID", nullable = false, precision = 22, scale = 0)
	public int getStimulusId() {
		return this.stimulusId;
	}

	public void setStimulusId(int stimulusId) {
		this.stimulusId = stimulusId;
	}

}
