package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * StimulusType generated by hbm2java
 */
@Entity
@Table(name = "STIMULUS_TYPE")
public class StimulusType implements java.io.Serializable {

	private int stimulusTypeId;
	private String description;
	private Set<StimulusRel> stimulusRels = new HashSet<StimulusRel>(0);
	private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);

	public StimulusType() {
	}

	public StimulusType(String description, Set<StimulusRel> stimulusRels,
			Set<ResearchGroup> researchGroups) {
		this.description = description;
		this.stimulusRels = stimulusRels;
		this.researchGroups = researchGroups;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "STIMULUS_TYPE_ID", nullable = false, precision = 22, scale = 0)
	public int getStimulusTypeId() {
		return this.stimulusTypeId;
	}

	public void setStimulusTypeId(int stimulusTypeId) {
		this.stimulusTypeId = stimulusTypeId;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stimulusType")
	public Set<StimulusRel> getStimulusRels() {
		return this.stimulusRels;
	}

	public void setStimulusRels(Set<StimulusRel> stimulusRels) {
		this.stimulusRels = stimulusRels;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "STIMULUS_TYPE_GROUP_REL", joinColumns = { @JoinColumn(name = "STIMULUS_TYPE_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, updatable = false) })
	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}

}
