package cz.zcu.kiv.eegdatabase.data.pojo;

// Generated 2.12.2013 0:56:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WeatherGroupRel generated by hbm2java
 */
@Entity
@Table(name = "WEATHER_GROUP_REL")
public class WeatherGroupRel implements java.io.Serializable {

	private WeatherGroupRelId id;
	private ResearchGroup researchGroup;
	private Weather weather;

	public WeatherGroupRel() {
	}

	public WeatherGroupRel(WeatherGroupRelId id, ResearchGroup researchGroup,
			Weather weather) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.weather = weather;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "weatherId", column = @Column(name = "WEATHER_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "researchGroupId", column = @Column(name = "RESEARCH_GROUP_ID", nullable = false, precision = 22, scale = 0)) })
	public WeatherGroupRelId getId() {
		return this.id;
	}

	public void setId(WeatherGroupRelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_GROUP_ID", nullable = false, insertable = false, updatable = false)
	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WEATHER_ID", nullable = false, insertable = false, updatable = false)
	public Weather getWeather() {
		return this.weather;
	}

	public void setWeather(Weather weather) {
		this.weather = weather;
	}

}
