package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Entity;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Fields;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;

/**
 * FileMetadataParamDef generated by hbm2java
 */
//@Entity
//@Indexed
public class FileMetadataParamDef implements java.io.Serializable {
//@DocumentId
  private int fileMetadataParamDefId;
//  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "FILEPARAMNAME")}) //use a different field name
  private String paramName;
//  @Fields({
//    @Field(index = Index.TOKENIZED), //same property indexed multiple times
//    @Field(name = "FILEPARAMDATATYPE")}) //use a different field name
  private String paramDataType;
  private Set<FileMetadataParamVal> fileMetadataParamVals = new HashSet<FileMetadataParamVal>(0);

  public FileMetadataParamDef() {
  }

  public FileMetadataParamDef(int fileMetadataParamDefId, String paramName, String paramDataType) {
    this.fileMetadataParamDefId = fileMetadataParamDefId;
    this.paramName = paramName;
    this.paramDataType = paramDataType;
  }

  public FileMetadataParamDef(int fileMetadataParamDefId, String paramName, String paramDataType, Set<FileMetadataParamVal> fileMetadataParamVals) {
    this.fileMetadataParamDefId = fileMetadataParamDefId;
    this.paramName = paramName;
    this.paramDataType = paramDataType;
    this.fileMetadataParamVals = fileMetadataParamVals;
  }

  public int getFileMetadataParamDefId() {
    return this.fileMetadataParamDefId;
  }

  public void setFileMetadataParamDefId(int fileMetadataParamDefId) {
    this.fileMetadataParamDefId = fileMetadataParamDefId;
  }

  public String getParamName() {
    return this.paramName;
  }

  public void setParamName(String paramName) {
    this.paramName = paramName;
  }

  public String getParamDataType() {
    return this.paramDataType;
  }

  public void setParamDataType(String paramDataType) {
    this.paramDataType = paramDataType;
  }

  public Set<FileMetadataParamVal> getFileMetadataParamVals() {
    return this.fileMetadataParamVals;
  }

  public void setFileMetadataParamVals(Set<FileMetadataParamVal> fileMetadataParamVals) {
    this.fileMetadataParamVals = fileMetadataParamVals;
  }
}


