package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.hibernate.annotations.Entity;
import org.hibernate.search.annotations.*;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
@Entity
@Indexed
@Analyzer(impl = StandardAnalyzer.class)
public class Person implements Serializable {

    @DocumentId
    private int personId;
    private String givenname;
    private String surname;
    private Timestamp dateOfBirth;
    private char gender;
    @Fields({
            @Field(index = Index.TOKENIZED), //same property indexed multiple times
            @Field(name = "email"),
            @Field(store = Store.YES)}) //use a different field name
    private String email;
    private String phoneNumber;
    private Timestamp registrationDate;
    private String authenticationHash;
    private boolean confirmed;
    @Fields({
            @Field(index = Index.TOKENIZED), //same property indexed multiple times
            @Field(name = "note"),
            @Field(store = Store.YES)}) //use a different field name
    private String note;
    private String username;
    private String password;
    private String authority;
    private ResearchGroup defaultGroup;
    private Set<VisualImpairment> visualImpairments = new HashSet<VisualImpairment>(0);
    private Set<Experiment> experiments = new HashSet<Experiment>(0);
    private Set<ResearchGroupMembership> researchGroupMemberships = new HashSet<ResearchGroupMembership>(0);
    private Set<Scenario> scenarios = new HashSet<Scenario>(0);
    private Set<Experiment> experimentsForOwnerId = new HashSet<Experiment>(0);
    private Set<Experiment> experimentsForSubjectPersonId = new HashSet<Experiment>(0);
    private Set<PersonOptParamVal> personOptParamVals = new HashSet<PersonOptParamVal>(0);
    private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);
    private Set<HearingImpairment> hearingImpairments = new HashSet<HearingImpairment>(0);
    private Set<GroupPermissionRequest> requests = new HashSet<GroupPermissionRequest>(0);
    private Set<History> histories = new HashSet<History>(0);
    private Set<Article> articlesSubscribtions = new HashSet<Article>(0);
    private Set<ResearchGroup> articlesGroupSubscribtions = new HashSet<ResearchGroup>(0);
    private Integer facebookId;


    public Person() {
    }

    public Person(int personId, String surname, char gender) {
        this.personId = personId;
        this.surname = surname;
        this.gender = gender;
    }

    public Person(int personId, String givenname, String surname, Timestamp dateOfBirth, char gender, String email, String phoneNumber, String note, String username, String password, String authority, Set<VisualImpairment> visualImpairments, Set<Experiment> experiments, Set<ResearchGroupMembership> researchGroupMemberships, Set<Scenario> scenarios, Set<Experiment> experimentsForOwnerId, Set<Experiment> experimentsForSubjectPersonId, Set<PersonOptParamVal> personOptParamVals, Set<ResearchGroup> researchGroups, Set<HearingImpairment> hearingImpairments) {
        this.personId = personId;
        this.givenname = givenname;
        this.surname = surname;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.note = note;
        this.username = username;
        this.password = password;
        this.authority = authority;
        this.visualImpairments = visualImpairments;
        this.experiments = experiments;
        this.researchGroupMemberships = researchGroupMemberships;
        this.scenarios = scenarios;
        this.experimentsForOwnerId = experimentsForOwnerId;
        this.experimentsForSubjectPersonId = experimentsForSubjectPersonId;
        this.personOptParamVals = personOptParamVals;
        this.researchGroups = researchGroups;
        this.hearingImpairments = hearingImpairments;
    }

    public int getPersonId() {
        return this.personId;
    }

    public void setPersonId(int personId) {
        this.personId = personId;
    }

    public String getGivenname() {
        return this.givenname;
    }

    public void setGivenname(String givenname) {
        this.givenname = givenname;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Timestamp getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Timestamp dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public char getGender() {
        return this.gender;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAuthority() {
        return this.authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }

    public Set<VisualImpairment> getVisualImpairments() {
        return this.visualImpairments;
    }

    public void setVisualImpairments(Set<VisualImpairment> visualImpairments) {
        this.visualImpairments = visualImpairments;
    }

    public Set<Experiment> getExperiments() {
        return this.experiments;
    }

    public void setExperiments(Set<Experiment> experiments) {
        this.experiments = experiments;
    }

    public Set<ResearchGroupMembership> getResearchGroupMemberships() {
        return this.researchGroupMemberships;
    }

    public void setResearchGroupMemberships(Set<ResearchGroupMembership> researchGroupMemberships) {
        this.researchGroupMemberships = researchGroupMemberships;
    }

    public Set<Scenario> getScenarios() {
        return this.scenarios;
    }

    public void setScenarios(Set<Scenario> scenarios) {
        this.scenarios = scenarios;
    }

    public Set<Experiment> getExperimentsForOwnerId() {
        return this.experimentsForOwnerId;
    }

    public void setExperimentsForOwnerId(Set<Experiment> experimentsForOwnerId) {
        this.experimentsForOwnerId = experimentsForOwnerId;
    }

    public Set<Experiment> getExperimentsForSubjectPersonId() {
        return this.experimentsForSubjectPersonId;
    }

    public void setExperimentsForSubjectPersonId(Set<Experiment> experimentsForSubjectPersonId) {
        this.experimentsForSubjectPersonId = experimentsForSubjectPersonId;
    }

    public Set<PersonOptParamVal> getPersonOptParamVals() {
        return this.personOptParamVals;
    }

    public void setPersonOptParamVals(Set<PersonOptParamVal> personOptParamVals) {
        this.personOptParamVals = personOptParamVals;
    }

    public Set<ResearchGroup> getResearchGroups() {
        return this.researchGroups;
    }

    public void setResearchGroups(Set<ResearchGroup> researchGroups) {
        this.researchGroups = researchGroups;
    }

    public Set<HearingImpairment> getHearingImpairments() {
        return this.hearingImpairments;
    }

    public void setHearingImpairments(Set<HearingImpairment> hearingImpairments) {
        this.hearingImpairments = hearingImpairments;
    }

    public ResearchGroup getDefaultGroup() {
        return defaultGroup;
    }

    public void setDefaultGroup(ResearchGroup defaultGroup) {
        this.defaultGroup = defaultGroup;
    }

    public Timestamp getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Timestamp registrationDate) {
        this.registrationDate = registrationDate;
    }

    public boolean isConfirmed() {
        return confirmed;
    }

    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    public String getAuthenticationHash() {
        return authenticationHash;
    }

    public void setAuthenticationHash(String authenticationHash) {
        this.authenticationHash = authenticationHash;
    }

    public Set<History> getHistories() {
        return histories;
    }

    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }

    public Set<GroupPermissionRequest> getRequests() {
        return requests;
    }

    public void setRequests(Set<GroupPermissionRequest> requests) {
        this.requests = requests;
    }

    public Set<Article> getArticlesSubscribtions() {
        return articlesSubscribtions;
    }

    public void setArticlesSubscribtions(Set<Article> articlesSubscribtions) {
        this.articlesSubscribtions = articlesSubscribtions;
    }

    public Set<ResearchGroup> getArticlesGroupSubscribtions() {
        return articlesGroupSubscribtions;
    }

    public void setArticlesGroupSubscribtions(Set<ResearchGroup> articlesGroupSubscribtions) {
        this.articlesGroupSubscribtions = articlesGroupSubscribtions;
    }

    public Integer getFacebookId() {
        return facebookId;
    }

    public void setFacebookId(Integer facebookId) {
        this.facebookId = facebookId;
    }

}


