package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA



/**
 * PersonOptParamValId generated by hbm2java
 */
public class PersonOptParamValId  implements java.io.Serializable {


     private int personId;
     private int personAdditionalParamId;

    public PersonOptParamValId() {
    }

    public PersonOptParamValId(int personId, int personAdditionalParamId) {
       this.personId = personId;
       this.personAdditionalParamId = personAdditionalParamId;
    }
   
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }
    public int getPersonAdditionalParamId() {
        return this.personAdditionalParamId;
    }
    
    public void setPersonAdditionalParamId(int personAdditionalParamId) {
        this.personAdditionalParamId = personAdditionalParamId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonOptParamValId) ) return false;
		 PersonOptParamValId castOther = ( PersonOptParamValId ) other; 
         
		 return (this.getPersonId()==castOther.getPersonId())
 && (this.getPersonAdditionalParamId()==castOther.getPersonAdditionalParamId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPersonId();
         result = 37 * result + this.getPersonAdditionalParamId();
         return result;
   }   


}


