package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 15.1.2011 15:15:26 by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private int reservationId;
     private ResearchGroup researchGroup;
     private Person person;
     private Timestamp creationTime;
     private Timestamp startTime;
     private Timestamp endTime;

    public Reservation() {
    }

	
    public Reservation(int reservationId) {
        this.reservationId = reservationId;
    }
    public Reservation(int reservationId, ResearchGroup researchGroup, Person person, Timestamp creationTime, Timestamp startTime, Timestamp endTime) {
       this.reservationId = reservationId;
       this.researchGroup = researchGroup;
       this.person = person;
       this.creationTime = creationTime;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public int getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(int reservationId) {
        this.reservationId = reservationId;
    }
    public ResearchGroup getResearchGroup() {
        return this.researchGroup;
    }
    
    public void setResearchGroup(ResearchGroup researchGroup) {
        this.researchGroup = researchGroup;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Timestamp getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Timestamp creationTime) {
        this.creationTime = creationTime;
    }
    public Timestamp getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }
    public Timestamp getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }




}


