package cz.zcu.kiv.eegdatabase.data.pojo;
// Generated 19.1.2010 23:18:53 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Entity;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Fields;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;

/**
 * VisualImpairment generated by hbm2java
 */
@Indexed
@Entity
public class VisualImpairment implements java.io.Serializable {
@DocumentId
  private int visualImpairmentId;
  @Fields({
    @Field(index = Index.TOKENIZED), //same property indexed multiple times
    @Field(name = "VISUALIMPAIRMENTDESCRIPTION")}) //use a different field name
  private String description;
  private Set<Person> persons = new HashSet<Person>(0);

  public VisualImpairment() {
  }

  public VisualImpairment(int visualImpairmentId, String description) {
    this.visualImpairmentId = visualImpairmentId;
    this.description = description;
  }

  public VisualImpairment(int visualImpairmentId, String description, Set<Person> persons) {
    this.visualImpairmentId = visualImpairmentId;
    this.description = description;
    this.persons = persons;
  }

  public int getVisualImpairmentId() {
    return this.visualImpairmentId;
  }

  public void setVisualImpairmentId(int visualImpairmentId) {
    this.visualImpairmentId = visualImpairmentId;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Set<Person> getPersons() {
    return this.persons;
  }

  public void setPersons(Set<Person> persons) {
    this.persons = persons;
  }
}


