ALTER TABLE "ANALYSIS_GROUP_REL" ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ARTEFACT_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ARTEFACT_RMVNG_MTHD_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "DIGITIZATION_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "DISEASE_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "EDUCATION_LEVEL_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_FIX_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_LOCATION_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_SYSTEM_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_TYPE_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "PHARMACEUTICAL_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "PROJECT_TYPE_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "SOFTWARE_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "STIMULUS_TYPE_GROUP_REL"  ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");

