ALTER TABLE "ANALYSIS_GROUP_REL" ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ANALYSIS_GROUP_REL" ADD CONSTRAINT ANALYSIS_ID_fk FOREIGN KEY ("ANALYSIS_ID") REFERENCES "ANALYSIS" ("ANALYSIS_ID");

ALTER TABLE "ARTEFACT_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ARTEFACT_GROUP_REL"  ADD CONSTRAINT ARTEFACT_ID_fk FOREIGN KEY ("ARTEFACT_ID") REFERENCES "ARTEFACT" ("ARTEFACT_ID");

ALTER TABLE "ARTEFACT_RMVNG_MTHD_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ARTEFACT_RMVNG_MTHD_GROUP_REL"  ADD CONSTRAINT ARTEFACT_RMVNG_MTHD_ID_fk FOREIGN KEY ("ARTEFACT_REMOVING_METHOD_ID") REFERENCES "ARTEFACT_REMOVING_METHOD" ("ARTEFACT_REMOVING_METHOD_ID");

ALTER TABLE "DIGITIZATION_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "DIGITIZATION_GROUP_REL"  ADD CONSTRAINT DIGITIZATION_ID_fk  FOREIGN KEY ("DIGITIZATION_ID") REFERENCES "DIGITIZATION" ("DIGITIZATION_ID");

ALTER TABLE "DISEASE_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "DISEASE_GROUP_REL"  ADD CONSTRAINT DISEASE_ID_fk  FOREIGN KEY ("DISEASE_ID") REFERENCES "DISEASE" ("DISEASE_ID");

ALTER TABLE "EDUCATION_LEVEL_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "EDUCATION_LEVEL_GROUP_REL"  ADD CONSTRAINT EDUCATION_LEVEL_ID_fk FOREIGN KEY ("EDUCATION_LEVEL_ID") REFERENCES "EDUCATION_LEVEL" ("EDUCATION_LEVEL_ID");

ALTER TABLE "ELECTRODE_FIX_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_FIX_GROUP_REL"  ADD CONSTRAINT ELECTRODE_FIX_ID_fk FOREIGN KEY ("ELECTRODE_FIX_ID") REFERENCES "ELECTRODE_FIX" ("ELECTRODE_FIX_ID");

ALTER TABLE "ELECTRODE_LOCATION_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_LOCATION_GROUP_REL"  ADD CONSTRAINT ELECTRODE_LOCATION_ID_fk FOREIGN KEY ("ELECTRODE_LOCATION_ID") REFERENCES "ELECTRODE_LOCATION" ("ELECTRODE_LOCATION_ID");

ALTER TABLE "ELECTRODE_SYSTEM_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_SYSTEM_GROUP_REL"  ADD CONSTRAINT ELECTRODE_SYSTEM_ID_fk FOREIGN KEY ("ELECTRODE_SYSTEM_ID") REFERENCES "ELECTRODE_SYSTEM" ("ELECTRODE_SYSTEM_ID");

ALTER TABLE "ELECTRODE_TYPE_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "ELECTRODE_TYPE_GROUP_REL"  ADD CONSTRAINT ELECTRODE_TYPE_ID_fk FOREIGN KEY ("ELECTRODE_TYPE_ID") REFERENCES "ELECTRODE_TYPE" ("ELECTRODE_TYPE_ID");

ALTER TABLE "PHARMACEUTICAL_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "PHARMACEUTICAL_GROUP_REL"  ADD CONSTRAINT PHARMACEUTICAL_ID_fk FOREIGN KEY ("PHARMACEUTICAL_ID") REFERENCES "PHARMACEUTICAL" ("PHARMACEUTICAL_ID");

ALTER TABLE "PROJECT_TYPE_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "PROJECT_TYPE_GROUP_REL"  ADD CONSTRAINT PROJECT_TYPE_ID_fk FOREIGN KEY ("PROJECT_TYPE_ID") REFERENCES "PROJECT_TYPE" ("PROJECT_TYPE_ID");

ALTER TABLE "SOFTWARE_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "SOFTWARE_GROUP_REL"  ADD CONSTRAINT SOFTWARE_ID_fk FOREIGN KEY ("SOFTWARE_ID") REFERENCES "SOFTWARE" ("SOFTWARE_ID");

ALTER TABLE "STIMULUS_TYPE_GROUP_REL"  ADD CONSTRAINT RESEARCH_GROUP_ID_fk FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID");
ALTER TABLE "STIMULUS_TYPE_GROUP_REL"  ADD CONSTRAINT STIMULUS_TYPE_ID_fk FOREIGN KEY ("STIMULUS_TYPE_ID") REFERENCES "STIMULUS_TYPE" ("STIMULUS_TYPE_ID");









