package cz.zcu.kiv.eegdatabase.webservices.EDPClient;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-27T23:01:21.234+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "ProcessServiceImplService", 
                  wsdlLocation = "file:/C:/Users/Petr/Documents/Development/EDP Client/src/main/java/cz/zcu/kiv/edpclient/generated/processService.wsdl",
                  targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/") 
public class ProcessServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.eegprocessor.kiv.zcu.cz/", "ProcessServiceImplService");
    public final static QName ProcessServiceImplPort = new QName("http://webservice.eegprocessor.kiv.zcu.cz/", "ProcessServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Petr/Documents/Development/EDP Client/src/main/java/cz/zcu/kiv/edpclient/generated/processService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProcessServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Petr/Documents/Development/EDP Client/src/main/java/cz/zcu/kiv/edpclient/generated/processService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProcessServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProcessServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ProcessService
     */
    @WebEndpoint(name = "ProcessServiceImplPort")
    public ProcessService getProcessServiceImplPort() {
        return super.getPort(ProcessServiceImplPort, ProcessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessService
     */
    @WebEndpoint(name = "ProcessServiceImplPort")
    public ProcessService getProcessServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ProcessServiceImplPort, ProcessService.class, features);
    }

}
