package cz.zcu.kiv.eegdatabase.webservices.EDPClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-27T23:01:21.216+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", name = "ProcessService")

public interface ProcessService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processData", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.ProcessData")
    @WebMethod
    @ResponseWrapper(localName = "processDataResponse", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.ProcessDataResponse")
    public byte[] processData(
            @WebParam(name = "arg0", targetNamespace = "")
            java.util.List<DataFile> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            SupportedFormat arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            java.util.List<String> arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMethodParameters", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.GetMethodParameters")
    @WebMethod
    @ResponseWrapper(localName = "getMethodParametersResponse", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.GetMethodParametersResponse")
    public java.util.List<MethodParameters> getMethodParameters(
            @WebParam(name = "arg0", targetNamespace = "")
            SupportedFormat arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAvailableMethods", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.GetAvailableMethods")
    @WebMethod
    @ResponseWrapper(localName = "getAvailableMethodsResponse", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.GetAvailableMethodsResponse")
    public java.util.List<String> getAvailableMethods();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "availableProcessingUnits", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.AvailableProcessingUnits")
    @WebMethod
    @ResponseWrapper(localName = "availableProcessingUnitsResponse", targetNamespace = "http://webservice.eegprocessor.kiv.zcu.cz/", className = "cz.zcu.kiv.edpclient.generated.AvailableProcessingUnitsResponse")
    public int availableProcessingUnits();
}
