CREATE TABLE "ARTEFACT_RMVNG_MTHD_GROUP_REL" (
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"ARTEFACT_REMOVING_METHOD_ID" INTEGER NOT NULL ,
PRIMARY KEY ("ARTEFACT_REMOVING_METHOD_ID", "RESEARCH_GROUP_ID") 
)
;
