@insert_into_HEARING_IMPAIRMENT.sql
@insert_into_VISUAL_IMPAIRMENT.sql
@insert_into_WEATHER.sql
@insert_into_HARDWARE.sql
@insert_into_PERSON_OPT_PARAM_DEF.sql
@insert_into_EXPERIMENT_OPT_PARAM_DEF.sql
@insert_into_PERSON.sql
@insert_into_RESEARCH_GROUP.sql
@insert_into_VISUAL_IMPAIRMENT_REL.sql
@insert_into_HEARING_IMPAIRMENT_REL.sql
@insert_into_RESEARCH_GROUP_MEMBERSHIP.sql
@insert_into_SCENARIO.sql
@insert_into_EXPERIMENT.sql
@insert_into_COEXPERIMENTER_REL.sql
@insert_into_HARDWARE_USAGE_REL.sql
@insert_into_DATA_FILE.sql
@insert_into_NEWS.sql
@insert_into_OPINION.sql
@insert_into_HISTORY.sql
@insert_into_EXPERIMENT_OPT_PARAM_VAL.sql
@insert_into_PERSON_OPT_PARAM_VAL.sql
@insert_into_FILE_METADATA_PARAM_DEF.sql
@insert_into_FILE_METADATA_PARAM_VAL.sql