INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(1, 'Roman', 'Mou�ek', TO_DATE('5.6.1975', 'DD.MM.RR'), 'M', 'moucek@kiv.zcu.cz', 784554201, 'moucek', 'moucek', 'ROLE_ADMIN',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(2, 'Petr', 'Je�ek', TO_DATE('5.5.1984', 'DD.MM.RR'), 'M', 'jezekp@kiv.zcu.cz', 784554207, 'pitrs', 'pitrs', 'ROLE_ADMIN',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(3, 'Pavel', 'Mautner', TO_DATE('5.5.1970', 'DD.MM.RR'), 'M', 'mautner@kiv.zcu.cz', 784554202, 'pavel', 'pavel', 'ROLE_ADMIN',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(4, 'Petr', 'Br�ha', TO_DATE('30.8.1987', 'DD.MM.RR'), 'M', 'BruhaP@seznam.cz', 732907550, 'pbruha', 'pbruha', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(5, 'Jan', '�t�bet�k', TO_DATE('1.7.1987', 'DD.MM.RR'), 'M', 'stebjan@students.zcu.cz', 723226612, 'stebjan', 'stebjan', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(6, 'Ji��', 'Vla�imsk�', TO_DATE('5.6.1987', 'DD.MM.RR'), 'M', 'jvlasims@students.zcu.cz', 784554203, 'jvlasims', 'jvlasims', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(7, 'Miroslav', 'Bro�ek', TO_DATE('12.3.1987','DD.MM.RR'), 'M', 'Barbarez@seznam.cz', 784554212, 'barbarez', 'barbarez', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(8, 'Radka', 'Havlenov�', TO_DATE('1.1.1986', 'DD.MM.RR'),'F', 'radka@seznam.cz', 784555601, 'radka', 'radka', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(9, 'Luk�', 'Va�eka', TO_DATE('10.4.1987', 'DD.MM.RR'), 'M', 'lukas.vareka@seznam.cz', 784554207, 'vareka', 'vareka', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(10, 'David', 'Br�ha', TO_DATE('6.2.1982', 'DD.MM.RR'), 'M', 'bruno@seznam.cz', 784554791, 'bruna', 'bruna', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(11, 'Jind�ich', 'Pergler', TO_DATE('6.2.1987', 'DD.MM.RR'), 'M', 'viper@seznam.cz', 784557591, 'jpergler', 'jpergler', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(12, 'Martin', 'Soutor', TO_DATE('3.10.1987', 'DD.MM.RR'), 'M', 'souty@seznam.cz', 784457591, 'souty', 'souty', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(13, 'Jind�ich', 'K�ivka', TO_DATE('10.11.1987', 'DD.MM.RR'), 'M', 'krovak@seznam.cz', 784556591, 'krivka', 'krivka', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(14, 'Pavel', 'P�edota', TO_DATE('8.8.1987','DD.MM.RR'), 'M', 'predy@seznam.cz', 784551591, 'predy', 'predy', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(15, 'Monika', 'Honsov�', TO_DATE('1.7.1987', 'DD.MM.RR'), 'F', 'moni@seznam.cz', 784557621, 'moni', 'moni', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(16, 'V�ra', 'Vinick�', TO_DATE('27.8.1987', 'DD.MM.RR'), 'F', 'winie@seznam.cz', 784657591, 'winie', 'winie', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(17, 'Barbora', 'Mikol�kov�', TO_DATE('1.2.1988', 'DD.MM.RR'), 'F', 'bara@seznam.cz', 784557521, 'bara', 'bara', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(18, 'Kate�ina', 'Ledinsk�', TO_DATE('8.12.1989', 'DD.MM.RR'), 'F', 'katuch@seznam.cz', 783557591, 'katuch', 'katuch', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(19, 'Veronika', 'Chmela�ov�', TO_DATE('6.3.1986', 'DD.MM.RR'), 'F', 'viper@seznam.cz', 784577591, 'werik', 'werik', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(20, 'Petr', 'Hump�l', TO_DATE('3.4.1987', 'DD.MM.RR'), 'M', 'cube@seznam.cz', 784557391, 'cube', 'cube', 'ROLE_USER',1);

INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(21, 'Lucie', 'Kol��ov�', TO_DATE('10.5.1985','DD.MM.RR'), 'F', 'lamborghiny.diablo@seznam.cz', 732557391, 'lucinka', 'lucinka', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(22, 'Lenka', 'Mal�', TO_DATE('5.8.1987','DD.MM.RR'), 'F', 'malicka@seznam.cz', 732557392, 'lenicka', 'lenicka', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(23, 'Ji��', 'Mat�jovic', TO_DATE('10.10.1987','DD.MM.RR'), 'M', 'matejka@seznam.cz', 732557393, 'matejovic', 'matejovic', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(24, 'Jan', 'Blahn�k', TO_DATE('4.9.1986','DD.MM.RR'), 'M', 'blaho@seznam.cz', 732557394, 'blaho', 'blaho', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(25, 'V�clav', 'Du�ek', TO_DATE('3.1.1987','DD.MM.RR'), 'M', 'dusin@seznam.cz', 732557395, 'dusin', 'dusin', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(26, 'Radmila', 'Dobr�', TO_DATE('10.5.1986','DD.MM.RR'), 'F', 'radulka@seznam.cz', 732557396, 'radmilka', 'radmilka', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(27, 'Tereza', 'Pazdern�kov�', TO_DATE('10.4.1985','DD.MM.RR'), 'F', 'terezka@seznam.cz', 732557397, 'terka', 'terka', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(28, 'Lucie', 'Bal��kov�', TO_DATE('2.3.1985','DD.MM.RR'), 'F', 'lucik@seznam.cz', 732557398, 'lucik', 'lucik', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(29, 'Lucie', 'Pivo�kov�', TO_DATE('5.11.1987','DD.MM.RR'), 'F', 'luciep@seznam.cz', 732557399, 'lucikp', 'lucikp', 'ROLE_USER',1);
INSERT INTO PERSON(PERSON_ID, GIVENNAME, SURNAME, DATE_OF_BIRTH, GENDER, EMAIL, PHONE_NUMBER, USERNAME, PASSWORD, AUTHORITY,CONFIRM)
VALUES(30, 'Lucie', 'Kylbergerov�', TO_DATE('29.8.1986','DD.MM.RR'), 'F', 'kylbergerova@seznam.cz', 732557311, 'luciek', 'luciek', 'ROLE_USER',1);