INSERT INTO HEARING_IMPAIRMENT(HEARING_IMPAIRMENT_ID, DESCRIPTION) VALUES(1, 'neslysi');
INSERT INTO HEARING_IMPAIRMENT(HEARING_IMPAIRMENT_ID, DESCRIPTION) VALUES(2, 'neslysi na leve ucho');
INSERT INTO HEARING_IMPAIRMENT(HEARING_IMPAIRMENT_ID, DESCRIPTION) VALUES(3, 'neslysi na prave ucho');