INSERT INTO ARTICLES_SUBSCRIBTIONS(ARTICLE_ID,PERSON_ID)VALUES(1,1);
INSERT INTO ARTICLES_SUBSCRIBTIONS(ARTICLE_ID,PERSON_ID)VALUES(2,2);
INSERT INTO ARTICLES_SUBSCRIBTIONS(ARTICLE_ID,PERSON_ID)VALUES(3,2);
