INSERT INTO SCENARIO_SCHEMA VALUES (1, 'scenarios.xsd', NULL, NULL, NULL, NULL, NULL, 'y');
INSERT INTO SCENARIO_SCHEMA VALUES (2, 'p300.xsd', NULL, NULL, NULL, NULL, NULL, 'y');
INSERT INTO SCENARIO_SCHEMA VALUES (3, 'subjects.xsd', NULL, NULL, NULL, NULL, NULL, 'y');