INSERT INTO WEATHER(WEATHER_ID, TITLE, DESCRIPTION) VALUES(1, 'jasno', 'sviti slunce');
INSERT INTO WEATHER(WEATHER_ID, TITLE, DESCRIPTION) VALUES(2, 'zatazeno', 'nesviti slunce');
INSERT INTO WEATHER(WEATHER_ID, TITLE, DESCRIPTION) VALUES(3, 'prsi', 'obcas prehanky');
INSERT INTO WEATHER(WEATHER_ID, TITLE, DESCRIPTION) VALUES(4, 'boure', 'silny vitr');
INSERT INTO WEATHER(WEATHER_ID, TITLE, DESCRIPTION) VALUES(5, 'snezi', 'zima');