INSERT INTO SCENARIO_SCHEMA(SCHEMA_ID, SCHEMA_NAME) VALUES(1,'scenarios.xsd');
INSERT INTO SCENARIO_SCHEMA(SCHEMA_ID, SCHEMA_NAME) VALUES(2,'p300.xsd');
INSERT INTO SCENARIO_SCHEMA(SCHEMA_ID, SCHEMA_NAME) VALUES(3,'subjects.xsd');