INSERT INTO VISUAL_IMPAIRMENT(VISUAL_IMPAIRMENT_ID, DESCRIPTION) VALUES(1, 'nevidi');
INSERT INTO VISUAL_IMPAIRMENT(VISUAL_IMPAIRMENT_ID, DESCRIPTION) VALUES(2, 'kratkozraky');
INSERT INTO VISUAL_IMPAIRMENT(VISUAL_IMPAIRMENT_ID, DESCRIPTION) VALUES(3, 'dalekozraky');