INSERT INTO SCENARIO_SCHEMA(SCHEMA_ID, SCHEMA_NAME) VALUES(1,'scenarios.xsd',NULL,NULL,NULL,NULL,NULL,'y');
INSERT INTO SCENARIO_SCHEMA(SCHEMA_ID, SCHEMA_NAME) VALUES(2,'p300.xsd',NULL,NULL,NULL,NULL,NULL,'y');
INSERT INTO SCENARIO_SCHEMA(SCHEMA_ID, SCHEMA_NAME) VALUES(3,'subjects.xsd',NULL,NULL,NULL,NULL,NULL,'y');