CREATE TABLE "RESEARCH_GROUP" (
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"OWNER_ID" INTEGER NOT NULL ,
	"TITLE" VARCHAR2 (100) NOT NULL ,
	"DESCRIPTION" VARCHAR2 (250) NOT NULL ,
PRIMARY KEY ("RESEARCH_GROUP_ID")
)
;