CREATE TABLE "VISUAL_IMPAIRMENT_REL" (
	"VISUAL_IMPAIRMENT_ID" INTEGER NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
 CONSTRAINT "PK_VISUAL_IMPAIRMENT_REL" PRIMARY KEY ("VISUAL_IMPAIRMENT_ID","PERSON_ID")
)
;