ALTER TABLE "COEXPERIMENTER_REL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "HARDWARE_USAGE_REL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "DATA_FILE" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "EXPERIMENT_OPT_PARAM_VAL" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "HISTORY" ADD  FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "COEXPERIMENTER_REL" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("OWNER_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "HEARING_IMPAIRMENT_REL" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "VISUAL_IMPAIRMENT_REL" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "PERSON_OPT_PARAM_VAL" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "RESEARCH_GROUP" ADD  FOREIGN KEY ("OWNER_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "RESEARCH_GROUP_MEMBERSHIP" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("SUBJECT_PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "SCENARIO" ADD  FOREIGN KEY ("OWNER_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "HISTORY" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "ARTICLES" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "ARTICLES_COMMENTS" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "GROUP_PERMISSION_REQUEST" ADD  FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("SCENARIO_ID") REFERENCES "SCENARIO" ("SCENARIO_ID")
;

ALTER TABLE "HISTORY" ADD  FOREIGN KEY ("SCENARIO_ID") REFERENCES "SCENARIO" ("SCENARIO_ID")
;

ALTER TABLE "HARDWARE_USAGE_REL" ADD  FOREIGN KEY ("HARDWARE_ID") REFERENCES "HARDWARE" ("HARDWARE_ID")
;

ALTER TABLE "FILE_METADATA_PARAM_VAL" ADD  FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("DATA_FILE_ID")
;

ALTER TABLE "HISTORY" ADD  FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("DATA_FILE_ID")
;

ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("WEATHER_ID") REFERENCES "WEATHER" ("WEATHER_ID")
;

ALTER TABLE "HEARING_IMPAIRMENT_REL" ADD  FOREIGN KEY ("HEARING_IMPAIRMENT_ID") REFERENCES "HEARING_IMPAIRMENT" ("HEARING_IMPAIRMENT_ID")
;

ALTER TABLE "VISUAL_IMPAIRMENT_REL" ADD  FOREIGN KEY ("VISUAL_IMPAIRMENT_ID") REFERENCES "VISUAL_IMPAIRMENT" ("VISUAL_IMPAIRMENT_ID")
;

ALTER TABLE "PERSON_OPT_PARAM_VAL" ADD  FOREIGN KEY ("PERSON_OPT_PARAM_DEF_ID") REFERENCES "PERSON_OPT_PARAM_DEF" ("PERSON_OPT_PARAM_DEF_ID")
;

ALTER TABLE "EXPERIMENT_OPT_PARAM_VAL" ADD  FOREIGN KEY ("EXPERIMENT_OPT_PARAM_DEF_ID") REFERENCES "EXPERIMENT_OPT_PARAM_DEF" ("EXPERIMENT_OPT_PARAM_DEF_ID")
;

ALTER TABLE "FILE_METADATA_PARAM_VAL" ADD  FOREIGN KEY ("FILE_METADATA_PARAM_DEF_ID") REFERENCES "FILE_METADATA_PARAM_DEF" ("FILE_METADATA_PARAM_DEF_ID")
;

ALTER TABLE "RESEARCH_GROUP_MEMBERSHIP" ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "SCENARIO" ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "EXPERIMENT" ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "ARTICLES" ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "PERSON" ADD  FOREIGN KEY ("DEFAULT_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "GROUP_PERMISSION_REQUEST" ADD  FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "ARTICLES_COMMENTS" ADD  FOREIGN KEY ("ARTICLE_ID") REFERENCES "ARTICLES" ("ARTICLE_ID")
;

ALTER TABLE "ARTICLES_COMMENTS" ADD  FOREIGN KEY ("PARENT_ID") REFERENCES "ARTICLES_COMMENTS" ("COMMENT_ID")
;
