CREATE TABLE "HEARING_IMPAIRMENT" (
	"HEARING_IMPAIRMENT_ID" INTEGER NOT NULL ,
	"DESCRIPTION" VARCHAR2 (30) NOT NULL  CONSTRAINT "UNIQUE_HARING_DEFECT_DESCRIPTI" UNIQUE ,
 CONSTRAINT "PK_HEARING_IMPAIRMENT" PRIMARY KEY ("HEARING_IMPAIRMENT_ID")
)
;