CREATE TABLE "DATA_FILE" (
	"DATA_FILE_ID" INTEGER NOT NULL ,
	"SAMPLING_RATE" FLOAT NOT NULL ,
	"FILE_CONTENT" BLOB NOT NULL ,
	"EXPERIMENT_ID" INTEGER NOT NULL ,
	"MIMETYPE" VARCHAR2 (40) NOT NULL ,
	"FILENAME" VARCHAR2 (80) NOT NULL ,
 CONSTRAINT "PK_DATA_FILE" PRIMARY KEY ("DATA_FILE_ID")
)
;