CREATE TABLE KEYWORDS
  (
    KEYWORDS_ID NUMBER,
    KEYWORDS_TEXT VARCHAR2(1000 BYTE),
    RESEARCH_GROUP_ID NUMBER,
    PRIMARY KEY (KEYWORDS_ID),
    CONSTRAINT FK_RESEARCH_GROUP FOREIGN KEY (RESEARCH_GROUP_ID) REFERENCES RESEARCH_GROUP (RESEARCH_GROUP_ID) ENABLE
  )
  