CREATE TABLE "PERSON_OPT_PARAM_DEF" (
	"PERSON_OPT_PARAM_DEF_ID" INTEGER NOT NULL ,
	"PARAM_NAME" VARCHAR2 (30) NOT NULL ,
	"PARAM_DATA_TYPE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_PERSON_OPT_PARAM_DEF" PRIMARY KEY ("PERSON_OPT_PARAM_DEF_ID")
)
;