CREATE TABLE ARTICLES_GROUP_SUBSCRIBTIONS 
(
  PERSON_ID NUMBER NOT NULL 
, RESEARCH_GROUP_ID NUMBER NOT NULL 
, CONSTRAINT ARTICLES_GROUP_SUBSCRIBTI_PK PRIMARY KEY 
  (
    PERSON_ID 
  , RESEARCH_GROUP_ID 
  )
  ENABLE 
) 

ALTER TABLE ARTICLES_GROUP_SUBSCRIBTIONS
ADD CONSTRAINT ARTICLES_GROUP_SUBSCRIBTI_FK1 FOREIGN KEY
(
  PERSON_ID 
)
REFERENCES PERSON
(
  PERSON_ID 
)
ENABLE;

ALTER TABLE ARTICLES_GROUP_SUBSCRIBTIONS
ADD CONSTRAINT ARTICLES_GROUP_SUBSCRIBTI_FK2 FOREIGN KEY
(
  RESEARCH_GROUP_ID 
)
REFERENCES RESEARCH_GROUP
(
  RESEARCH_GROUP_ID 
)
ENABLE;
