CREATE TABLE "HISTORY" (
	"HISTORY_ID" INTEGER NOT NULL ,
	"EXPERIMENT_ID" INTEGER,
	"SCENARIO_ID" INTEGER,
	"PERSON_ID" INTEGER NOT NULL ,
	"DATA_FILE_ID" INTEGER,
	"TIME" DATE DEFAULT SYSDATE NOT NULL ,
 CONSTRAINT "PK_HISTORY" PRIMARY KEY ("HISTORY_ID")
)
;