CREATE TABLE "FILE_METADATA_PARAM_VAL" (
	"FILE_METADATA_PARAM_DEF_ID" INTEGER NOT NULL ,
	"DATA_FILE_ID" INTEGER NOT NULL ,
	"METADATA_VALUE" NVARCHAR2(30) NOT NULL ,
 CONSTRAINT "PK_FILE_METADATA_PARAM_VAL" PRIMARY KEY ("FILE_METADATA_PARAM_DEF_ID","DATA_FILE_ID")
)
;