CREATE TABLE "OPINION" (
	"OPINION_ID" INTEGER NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER,
	"MESSAGE" VARCHAR2 (4000) NOT NULL ,
	"TIME" DATE DEFAULT SYSDATE NOT NULL ,
	"TITLE" VARCHAR2 (100) NOT NULL ,
 CONSTRAINT "PK_OPINION" PRIMARY KEY ("OPINION_ID")
)
;