CREATE TABLE "HARDWARE" (
	"HARDWARE_ID" INTEGER NOT NULL ,
	"TITLE" VARCHAR2 (50) NOT NULL  CONSTRAINT "UNIQUE_HARDWARE_TITLE" UNIQUE ,
	"TYPE" VARCHAR2 (30) NOT NULL  CONSTRAINT "UNIQUE_HARDWARE_TYPE" UNIQUE ,
	"DESCRIPTION" VARCHAR2 (30) CONSTRAINT "UNIQUE_HARDWARE_DESCRIPTION" UNIQUE ,
 CONSTRAINT "PK_HARDWARE" PRIMARY KEY ("HARDWARE_ID")
)
;