@create_table_COEXPERIMENTAL_REL.sql
@create_table_DATA_FILE.sql
@create_table_EXPERIMENT.sql
@create_table_EXPERIMENT_OPT_PARAM_DEF.sql
@create_table_EXPERIMENT_OPT_PARAM_VAL.sql
@create_table_FILE_METADATA_PARAM_DEF.sql
@create_table_FILE_METADATA_PARAM_VAL.sql
@create_table_HARDWARE.sql
@create_table_HARDWARE_USAGE_REL.sql
@create_table_HEARING_IMPAIRMENT.sql
@create_table_HEARING_IMPAIRMENT_REL.sql
@create_table_HISTORY.sql
@create_table_NEWS.sql
@create_table_OPINION.sql
@create_table_PERSON.sql
@create_table_PERSON_OPT_PARAM_DEF.sql
@create_table_PERSON_OPT_PARAM_VAL.sql
@create_table_RESEARCH_GROUP.sql
@create_table_RESEARCH_GROUP_MEMBERSHIP.sql
@create_table_SCENARIO.sql
@create_table_VISUAL_IMPAIRMENT.sql
@create_table_VISUAL_IMPAIRMENT_REL.sql
@create_table_WEATHER.sql
@create_references.sql