CREATE TABLE "RESEARCH_GROUP_MEMBERSHIP" (
	"PERSON_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"AUTHORITY" VARCHAR2 (30) NOT NULL ,
PRIMARY KEY ("PERSON_ID","RESEARCH_GROUP_ID")
)
;