CREATE TABLE "FILE_METADATA_PARAM_DEF" (
	"PARAM_NAME" VARCHAR2 (30) NOT NULL ,
	"FILE_METADATA_PARAM_DEF_ID" INTEGER NOT NULL ,
	"PARAM_DATA_TYPE" VARCHAR2 (20) NOT NULL ,
PRIMARY KEY ("FILE_METADATA_PARAM_DEF_ID")
)
;