CREATE TABLE "HISTORY" (
	"HISTORY_ID" INTEGER NOT NULL ,
	"EXPERIMENT_ID" INTEGER,
	"SCENARIO_ID" INTEGER,
	"PERSON_ID" INTEGER NOT NULL ,
	"DATA_FILE_ID" INTEGER,
	"DATE_OF_DOWNLOAD" DATE DEFAULT SYSDATE NOT NULL ,
PRIMARY KEY ("HISTORY_ID")
)
;