CREATE TABLE "VISUAL_IMPAIRMENT" (
	"VISUAL_IMPAIRMENT_ID" INTEGER NOT NULL ,
	"DESCRIPTION" VARCHAR2 (30) NOT NULL  CONSTRAINT "UNIQUE_EYES_DEFECT_DESCRIPTION" UNIQUE ,
 CONSTRAINT "PK_VISUAL_IMPAIRMENT" PRIMARY KEY ("VISUAL_IMPAIRMENT_ID")
)
;