CREATE TABLE "EEGTEST"."USERCONNECTION"
  (
    "RANK"           NUMBER(*,0) NOT NULL ENABLE,
    "PROFILEURL"     VARCHAR2(512 BYTE),
    "IMAGEURL"       VARCHAR2(512 BYTE),
    "SECRET"         VARCHAR2(255 BYTE),
    "REFRESHTOKEN"   VARCHAR2(255 BYTE),
    "EXPIRETIME"     NUMBER(*,0),
    "PROVIDERID"     VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "PROVIDERUSERID" VARCHAR2(255 BYTE),
    "ACCESSTOKEN"    VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "DISPLAYNAME"    VARCHAR2(255 BYTE),
    "USERID"         VARCHAR2(255 BYTE) NOT NULL ENABLE,
    CONSTRAINT "USERCONNECTION_PK" PRIMARY KEY ("USERID", "PROVIDERID", "RANK") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "EEG_USERS" ENABLE
  )