CREATE TABLE "HEARING_IMPAIRMENT_REL" (
	"PERSON_ID" INTEGER NOT NULL ,
	"HEARING_IMPAIRMENT_ID" INTEGER NOT NULL ,
 CONSTRAINT "PK_HEARING_IMPAIRMENT_REL" PRIMARY KEY ("PERSON_ID","HEARING_IMPAIRMENT_ID")
)
;