CREATE TABLE "GROUP_PERMISSION_REQUEST" (
	"REQUEST_ID" INTEGER NOT NULL ,
	"REQUESTED_PERMISSION" VARCHAR2 (20) NOT NULL ,
	"GRANTED" NUMBER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
PRIMARY KEY ("REQUEST_ID")
)
;