CREATE TABLE "NEWS" (
	"NEWS_ID" INTEGER NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER,
	"MESSAGE" VARCHAR2 (4000) NOT NULL ,
	"TIME" DATE DEFAULT SYSDATE NOT NULL ,
	"TITLE" VARCHAR2 (100) NOT NULL ,
 CONSTRAINT "PK_NEWS" PRIMARY KEY ("NEWS_ID")
)
;