/*
CREATED		16.12.2008
MODIFIED		8.4.2010
PROJECT
MODEL
COMPANY
AUTHOR
VERSION
DATABASE		ORACLE 10G
*/


-- CREATE TYPES SECTION


-- CREATE TABLES SECTION


CREATE TABLE "EXPERIMENT" (
	"EXPERIMENT_ID" INTEGER NOT NULL ,
	"OWNER_ID" INTEGER NOT NULL ,
	"SUBJECT_PERSON_ID" INTEGER NOT NULL ,
	"SCENARIO_ID" INTEGER NOT NULL ,
	"WEATHER_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"START_TIME" DATE,
	"END_TIME" DATE,
	"TEMPERATURE" SMALLINT,
	"WEATHERNOTE" VARCHAR2 (255),
	"PRIVATE" INTEGER DEFAULT 0 NOT NULL ,
 CONSTRAINT "PK_EXPERIMENT" PRIMARY KEY ("EXPERIMENT_ID")
)
;

CREATE TABLE "PERSON" (
	"PERSON_ID" INTEGER NOT NULL ,
	"DEFAULT_GROUP_ID" INTEGER,
	"GIVENNAME" VARCHAR2 (50),
	"SURNAME" VARCHAR2 (50) NOT NULL ,
	"DATE_OF_BIRTH" DATE,
	"GENDER" CHAR (1) NOT NULL  CONSTRAINT "FILLED_GENDER" CHECK (GENDER = 'M' OR GENDER='F' ) ,
	"EMAIL" VARCHAR2 (50),
	"PHONE_NUMBER" VARCHAR2 (20),
	"NOTE" VARCHAR2 (255),
	"USERNAME" VARCHAR2 (50) UNIQUE ,
	"PASSWORD" VARCHAR2 (50),
	"AUTHORITY" VARCHAR2 (50),
	"CONFIRM" INTEGER DEFAULT 0,
 CONSTRAINT "PK_PERSON" PRIMARY KEY ("PERSON_ID")
)
;

CREATE TABLE "COEXPERIMENTER_REL" (
	"PERSON_ID" INTEGER NOT NULL ,
	"EXPERIMENT_ID" INTEGER NOT NULL ,
PRIMARY KEY ("PERSON_ID","EXPERIMENT_ID")
)
;

CREATE TABLE "SCENARIO" (
	"SCENARIO_ID" INTEGER NOT NULL ,
	"OWNER_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"TITLE" VARCHAR2 (40) CONSTRAINT "UNIQUE_SCENARIO_TITLE" UNIQUE ,
	"SCENARIO_LENGTH" SMALLINT,
	"SCENARIO_XML" CLOB,
	"DESCRIPTION" VARCHAR2 (255),
	"PRIVATE" INTEGER DEFAULT 0 NOT NULL ,
 CONSTRAINT "PK_SCENARIO" PRIMARY KEY ("SCENARIO_ID")
)
;

CREATE TABLE "HARDWARE" (
	"HARDWARE_ID" INTEGER NOT NULL ,
	"TITLE" VARCHAR2 (50) NOT NULL  CONSTRAINT "UNIQUE_HARDWARE_TITLE" UNIQUE ,
	"TYPE" VARCHAR2 (30) NOT NULL  CONSTRAINT "UNIQUE_HARDWARE_TYPE" UNIQUE ,
	"DESCRIPTION" VARCHAR2 (30) CONSTRAINT "UNIQUE_HARDWARE_DESCRIPTION" UNIQUE ,
 CONSTRAINT "PK_HARDWARE" PRIMARY KEY ("HARDWARE_ID")
)
;

CREATE TABLE "HARDWARE_USAGE_REL" (
	"HARDWARE_ID" INTEGER NOT NULL ,
	"EXPERIMENT_ID" INTEGER NOT NULL ,
 CONSTRAINT "PK_HARDWARE_USAGE_REL" PRIMARY KEY ("HARDWARE_ID","EXPERIMENT_ID")
)
;

CREATE TABLE "DATA_FILE" (
	"DATA_FILE_ID" INTEGER NOT NULL ,
	"SAMPLING_RATE" FLOAT NOT NULL ,
	"FILE_CONTENT" BLOB NOT NULL ,
	"EXPERIMENT_ID" INTEGER NOT NULL ,
	"MIMETYPE" VARCHAR2 (40) NOT NULL ,
	"FILENAME" VARCHAR2 (80) NOT NULL ,
 CONSTRAINT "PK_DATA_FILE" PRIMARY KEY ("DATA_FILE_ID")
)
;

CREATE TABLE "FILE_METADATA_PARAM_VAL" (
	"FILE_METADATA_PARAM_DEF_ID" INTEGER NOT NULL ,
	"DATA_FILE_ID" INTEGER NOT NULL ,
	"METADATA_VALUE" NVARCHAR2(30) NOT NULL ,
 CONSTRAINT "PK_FILE_METADATA_PARAM_VAL" PRIMARY KEY ("FILE_METADATA_PARAM_DEF_ID","DATA_FILE_ID")
)
;

CREATE TABLE "WEATHER" (
	"WEATHER_ID" INTEGER NOT NULL ,
	"DESCRIPTION" VARCHAR2 (30) CONSTRAINT "UNIQUE_WEATHER_DESCRIPTION" UNIQUE ,
	"TITLE" VARCHAR2 (30) NOT NULL  CONSTRAINT "UNIQUE_WHEATER_TITLE" UNIQUE ,
 CONSTRAINT "PK_WEATHER" PRIMARY KEY ("WEATHER_ID")
)
;

CREATE TABLE "HEARING_IMPAIRMENT" (
	"HEARING_IMPAIRMENT_ID" INTEGER NOT NULL ,
	"DESCRIPTION" VARCHAR2 (30) NOT NULL  CONSTRAINT "UNIQUE_HARING_DEFECT_DESCRIPTI" UNIQUE ,
 CONSTRAINT "PK_HEARING_IMPAIRMENT" PRIMARY KEY ("HEARING_IMPAIRMENT_ID")
)
;

CREATE TABLE "VISUAL_IMPAIRMENT" (
	"VISUAL_IMPAIRMENT_ID" INTEGER NOT NULL ,
	"DESCRIPTION" VARCHAR2 (30) NOT NULL  CONSTRAINT "UNIQUE_EYES_DEFECT_DESCRIPTION" UNIQUE ,
 CONSTRAINT "PK_VISUAL_IMPAIRMENT" PRIMARY KEY ("VISUAL_IMPAIRMENT_ID")
)
;

CREATE TABLE "HEARING_IMPAIRMENT_REL" (
	"PERSON_ID" INTEGER NOT NULL ,
	"HEARING_IMPAIRMENT_ID" INTEGER NOT NULL ,
 CONSTRAINT "PK_HEARING_IMPAIRMENT_REL" PRIMARY KEY ("PERSON_ID","HEARING_IMPAIRMENT_ID")
)
;

CREATE TABLE "VISUAL_IMPAIRMENT_REL" (
	"VISUAL_IMPAIRMENT_ID" INTEGER NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
 CONSTRAINT "PK_VISUAL_IMPAIRMENT_REL" PRIMARY KEY ("VISUAL_IMPAIRMENT_ID","PERSON_ID")
)
;

CREATE TABLE "PERSON_OPT_PARAM_DEF" (
	"PERSON_OPT_PARAM_DEF_ID" INTEGER NOT NULL ,
	"PARAM_NAME" VARCHAR2 (30) NOT NULL ,
	"PARAM_DATA_TYPE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_PERSON_OPT_PARAM_DEF" PRIMARY KEY ("PERSON_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "PERSON_OPT_PARAM_VAL" (
	"PARAM_VALUE" VARCHAR2 (30) NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
	"PERSON_OPT_PARAM_DEF_ID" INTEGER NOT NULL ,
 CONSTRAINT "PK_PERSON_OPT_PARAM_VAL" PRIMARY KEY ("PERSON_ID","PERSON_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "EXPERIMENT_OPT_PARAM_DEF" (
	"EXPERIMENT_OPT_PARAM_DEF_ID" INTEGER NOT NULL ,
	"PARAM_NAME" VARCHAR2 (30) NOT NULL ,
	"PARAM_DATA_TYPE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_EXPERIMENT_OPT_PARAM_DEF" PRIMARY KEY ("EXPERIMENT_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "EXPERIMENT_OPT_PARAM_VAL" (
	"PARAM_VALUE" VARCHAR2 (30) NOT NULL ,
	"EXPERIMENT_ID" INTEGER NOT NULL ,
	"EXPERIMENT_OPT_PARAM_DEF_ID" INTEGER NOT NULL ,
 CONSTRAINT "PK_EXPERIMENT_OPT_PARAM_VAL" PRIMARY KEY ("EXPERIMENT_ID","EXPERIMENT_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "FILE_METADATA_PARAM_DEF" (
	"PARAM_NAME" VARCHAR2 (30) NOT NULL ,
	"FILE_METADATA_PARAM_DEF_ID" INTEGER NOT NULL ,
	"PARAM_DATA_TYPE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_FILE_METADATA_PARAM_DEF" PRIMARY KEY ("FILE_METADATA_PARAM_DEF_ID")
)
;

CREATE TABLE "RESEARCH_GROUP" (
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"OWNER_ID" INTEGER NOT NULL ,
	"TITLE" VARCHAR2 (100) NOT NULL ,
	"DESCRIPTION" VARCHAR2 (250) NOT NULL ,
 CONSTRAINT "PK_RESEARCH_GROUP" PRIMARY KEY ("RESEARCH_GROUP_ID")
)
;

CREATE TABLE "RESEARCH_GROUP_MEMBERSHIP" (
	"PERSON_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER NOT NULL ,
	"AUTHORITY" VARCHAR2 (30) NOT NULL ,
 CONSTRAINT "PK_RESEARCH_GROUP_MEMBERSHIP" PRIMARY KEY ("PERSON_ID","RESEARCH_GROUP_ID")
)
;

CREATE TABLE "HISTORY" (
	"HISTORY_ID" INTEGER NOT NULL ,
	"EXPERIMENT_ID" INTEGER,
	"SCENARIO_ID" INTEGER,
	"PERSON_ID" INTEGER NOT NULL ,
	"DATA_FILE_ID" INTEGER,
	"TIME" DATE DEFAULT SYSDATE NOT NULL ,
 CONSTRAINT "PK_HISTORY" PRIMARY KEY ("HISTORY_ID")
)
;

CREATE TABLE "NEWS" (
	"NEWS_ID" INTEGER NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER,
	"MESSAGE" VARCHAR2 (4000) NOT NULL ,
	"TIME" DATE DEFAULT SYSDATE NOT NULL ,
	"TITLE" VARCHAR2 (100) NOT NULL ,
 CONSTRAINT "PK_NEWS" PRIMARY KEY ("NEWS_ID")
)
;

CREATE TABLE "OPINION" (
	"OPINION_ID" INTEGER NOT NULL ,
	"PERSON_ID" INTEGER NOT NULL ,
	"RESEARCH_GROUP_ID" INTEGER,
	"MESSAGE" VARCHAR2 (4000) NOT NULL ,
	"TIME" DATE DEFAULT SYSDATE NOT NULL ,
	"TITLE" VARCHAR2 (100) NOT NULL ,
 CONSTRAINT "PK_OPINION" PRIMARY KEY ("OPINION_ID")
)
;


-- CREATE ALTERNATE KEYS SECTION


-- CREATE FOREIGN KEYS SECTION

ALTER TABLE "COEXPERIMENTER_REL" ADD CONSTRAINT "STAFF_MEASURATION_ID_FK" FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "HARDWARE_USAGE_REL" ADD CONSTRAINT "USED_HARDWARE_ID_FK" FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "DATA_FILE" ADD CONSTRAINT "MEASURATION_ID_FK" FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "EXPERIMENT_OPT_PARAM_VAL" ADD CONSTRAINT "MEAS_ADD_PARAMS_VAL_ID_FK" FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "HISTORY" ADD CONSTRAINT "RELATIONSHIP43" FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID")
;

ALTER TABLE "COEXPERIMENTER_REL" ADD CONSTRAINT "STAFF_PERSON_ID_FK" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT "MEASURED_ID_FK" FOREIGN KEY ("OWNER_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "HEARING_IMPAIRMENT_REL" ADD CONSTRAINT "PERSON_HEARING_DEFECT_ID_FK" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "VISUAL_IMPAIRMENT_REL" ADD CONSTRAINT "PERSON_EYES_DEFECT_ID_FK" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "PERSON_OPT_PARAM_VAL" ADD CONSTRAINT "PERSON_ID_ADD_PARAMS_VAL_FK" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "RESEARCH_GROUP" ADD CONSTRAINT "OWNER_OF_GROUP" FOREIGN KEY ("OWNER_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "RESEARCH_GROUP_MEMBERSHIP" ADD CONSTRAINT "MEMBER_PERSON_ID" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT "MEASURATION_OWNER" FOREIGN KEY ("SUBJECT_PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "SCENARIO" ADD CONSTRAINT "SCENARIO_OWNER" FOREIGN KEY ("OWNER_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "HISTORY" ADD CONSTRAINT "RELATIONSHIP45" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "NEWS" ADD CONSTRAINT "NEW_OWNER" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "OPINION" ADD CONSTRAINT "OPINIONS_OWNER" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
;

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT "SCENARIO_ID_FK" FOREIGN KEY ("SCENARIO_ID") REFERENCES "SCENARIO" ("SCENARIO_ID")
;

ALTER TABLE "HISTORY" ADD CONSTRAINT "DOWNLOADED_SCENARIOS" FOREIGN KEY ("SCENARIO_ID") REFERENCES "SCENARIO" ("SCENARIO_ID")
;

ALTER TABLE "HARDWARE_USAGE_REL" ADD CONSTRAINT "HARDWARE_ID_FK" FOREIGN KEY ("HARDWARE_ID") REFERENCES "HARDWARE" ("HARDWARE_ID")
;

ALTER TABLE "FILE_METADATA_PARAM_VAL" ADD CONSTRAINT "FILE_METADATA_ID_PK" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("DATA_FILE_ID")
;

ALTER TABLE "HISTORY" ADD CONSTRAINT "DOWNLOADED_DATA" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("DATA_FILE_ID")
;

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT "WEATHER_ID_FK" FOREIGN KEY ("WEATHER_ID") REFERENCES "WEATHER" ("WEATHER_ID")
;

ALTER TABLE "HEARING_IMPAIRMENT_REL" ADD CONSTRAINT "HEARING_DEFECT_ID_FK" FOREIGN KEY ("HEARING_IMPAIRMENT_ID") REFERENCES "HEARING_IMPAIRMENT" ("HEARING_IMPAIRMENT_ID")
;

ALTER TABLE "VISUAL_IMPAIRMENT_REL" ADD CONSTRAINT "EYES_DEFECT_FK" FOREIGN KEY ("VISUAL_IMPAIRMENT_ID") REFERENCES "VISUAL_IMPAIRMENT" ("VISUAL_IMPAIRMENT_ID")
;

ALTER TABLE "PERSON_OPT_PARAM_VAL" ADD CONSTRAINT "PERSON_ADDITIONAL_PARAM_ID_FK" FOREIGN KEY ("PERSON_OPT_PARAM_DEF_ID") REFERENCES "PERSON_OPT_PARAM_DEF" ("PERSON_OPT_PARAM_DEF_ID")
;

ALTER TABLE "EXPERIMENT_OPT_PARAM_VAL" ADD CONSTRAINT "MEAS_ADD_PARAM_ID_FK" FOREIGN KEY ("EXPERIMENT_OPT_PARAM_DEF_ID") REFERENCES "EXPERIMENT_OPT_PARAM_DEF" ("EXPERIMENT_OPT_PARAM_DEF_ID")
;

ALTER TABLE "FILE_METADATA_PARAM_VAL" ADD CONSTRAINT "FILE_METADATA_PARAMS_ID_FK" FOREIGN KEY ("FILE_METADATA_PARAM_DEF_ID") REFERENCES "FILE_METADATA_PARAM_DEF" ("FILE_METADATA_PARAM_DEF_ID")
;

ALTER TABLE "RESEARCH_GROUP_MEMBERSHIP" ADD CONSTRAINT "MEMBER_GROUP_ID" FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "SCENARIO" ADD CONSTRAINT "INSERTED_IN_GROUP" FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT "EXPERIMENT_OWNER" FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "NEWS" ADD CONSTRAINT "GROUP_OWNER" FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "OPINION" ADD CONSTRAINT "GROUP_OPINIONS_OWNER" FOREIGN KEY ("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;

ALTER TABLE "PERSON" ADD CONSTRAINT "RELATIONSHIP53" FOREIGN KEY ("DEFAULT_GROUP_ID") REFERENCES "RESEARCH_GROUP" ("RESEARCH_GROUP_ID")
;


-- CREATE OBJECT TABLES SECTION


-- CREATE XMLTYPE TABLES SECTION


-- CREATE FUNCTIONS SECTION


-- CREATE SEQUENCES SECTION


-- CREATE PACKAGES SECTION


-- CREATE SYNONYMS SECTION


-- CREATE TABLE COMMENTS SECTION


-- CREATE ATTRIBUTE COMMENTS SECTION


