CREATE TABLE "ELECTRODE_TYPE" (
	"ELECTRODE_TYPE_ID" INTEGER NOT NULL ,
	"NAME" VARCHAR2 (150) NOT NULL,
	"DESC" VARCHAR2(300) NOT NULL,
	"IS_DEFAULT" INTEGER NOT NULL ,
PRIMARY KEY ("ELECTRODE_TYPE_ID")
)
;
