CREATE TABLE "ELECTRODE_FIX" (
	"ELECTRODE_FIX_ID" INTEGER NOT NULL,
	"NAME" VARCHAR2 (150) NOT NULL,
	"DESCRIPTION" VARCHAR2(300) NOT NULL ,
	"IS_DEFAULT" INTEGER NOT NULL ,
PRIMARY KEY ("ELECTRODE_FIX_ID")
)
;
