CREATE TABLE "DIGITIZATION" (
	"DIGITIZATION_ID" INTEGER NOT NULL ,
	"GAIN" INTEGER NOT NULL ,
	"FILTER" VARCHAR2(300) NOT NULL ,
	"SAMPLING_RATE" FLOAT NOT NULL ,
PRIMARY KEY ("DIGITIZATION_ID")
)
;
