CREATE TABLE "SOFTWARE" (
	"SOFTWARE_ID" INTEGER NOT NULL ,
	"TITLE" VARCHAR2 (150) NOT NULL ,
	"DESCRIPTION" VARCHAR2(300) NOT NULL ,
	"IS_DEFAULT" INTEGER NOT NULL ,
PRIMARY KEY ("SOFTWARE_ID")
)
;
