ALTER TABLE "PHARMACEUTICAL_REL" ADD CONSTRAINT EXPERIMENT_ID_fk FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "PHARMACEUTICAL_REL" ADD CONSTRAINT PHARMACEUTICAL_ID_fk FOREIGN KEY ("PHARMACEUTICAL_ID") REFERENCES "PHARMACEUTICAL" ("PHARMACEUTICAL_ID");

ALTER TABLE "DISEASE_REL" ADD CONSTRAINT EXPERIMENT_ID_fk FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "DISEASE_REL" ADD CONSTRAINT DISEASE_ID_fk FOREIGN KEY ("DISEASE_ID") REFERENCES "DISEASE" ("DISEASE_ID");

ALTER TABLE "PROJECT_TYPE_REL" ADD CONSTRAINT PROJECT_TYPE_ID_fk FOREIGN KEY ("PROJECT_TYPE_ID") REFERENCES "PROJECT_TYPE" ("PROJECT_TYPE_ID");
ALTER TABLE "PROJECT_TYPE_REL" ADD CONSTRAINT EXPERIMENT_ID_fk FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");

ALTER TABLE "STIMULUS_REL" ADD CONSTRAINT SCENARIO_ID_fk FOREIGN KEY ("SCENARIO_ID") REFERENCES "SCENARIO" ("SCENARIO_ID");
ALTER TABLE "STIMULUS_REL" ADD CONSTRAINT STIMULUS_TYPE_ID_fk FOREIGN KEY ("STIMULUS_TYPE_ID") REFERENCES "STIMULUS_TYPE" ("STIMULUS_TYPE_ID");
ALTER TABLE "STIMULUS_REL" ADD CONSTRAINT STIMULUS_ID_fk FOREIGN KEY ("STIMULUS_ID") REFERENCES "STIMULUS" ("STIMULUS_ID");


ALTER TABLE "DATA_FILE" ADD CONSTRAINT ANALYSIS_ID_fk FOREIGN KEY ("ANALYSIS_ID") REFERENCES "ANALYSIS" ("ANALYSIS_ID");

ALTER TABLE "SOFTWARE_REL" ADD CONSTRAINT EXPERIMENT_ID_fk FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "SOFTWARE_REL" ADD CONSTRAINT SOFTWARE_ID_fk FOREIGN KEY ("SOFTWARE_ID") REFERENCES "SOFTWARE" ("SOFTWARE_ID");

ALTER TABLE "ELECTRODE_LOCATION_REL" ADD CONSTRAINT ELECTRODE_CONF_ID_fk  FOREIGN KEY ("ELECTRODE_CONF_ID") REFERENCES "ELECTRODE_CONF" ("ELECTRODE_CONF_ID");
ALTER TABLE "ELECTRODE_LOCATION_REL" ADD CONSTRAINT ELECTRODE_LOCATION_ID_fk  FOREIGN KEY ("ELECTRODE_LOCATION_ID") REFERENCES "ELECTRODE_LOCATION" ("ELECTRODE_LOCATION_ID");

ALTER TABLE "ELECTRODE_LOCATION" ADD CONSTRAINT ELECTRODE_FIX_ID_fk FOREIGN KEY ("ELECTRODE_FIX_ID") REFERENCES "ELECTRODE_FIX" ("ELECTRODE_FIX_ID");
ALTER TABLE "ELECTRODE_LOCATION" ADD CONSTRAINT ELECTRODE_TYPE_ID_fk FOREIGN KEY ("ELECTRODE_TYPE_ID") REFERENCES "ELECTRODE_TYPE" ("ELECTRODE_TYPE_ID");

ALTER TABLE "ELECTRODE_CONF" ADD CONSTRAINT ELECTRODE_SYSTEM_ID_fk FOREIGN KEY ("ELECTRODE_SYSTEM_ID") REFERENCES "ELECTRODE_SYSTEM" ("ELECTRODE_SYSTEM_ID");
ALTER TABLE "ELECTRODE_CONF" ADD CONSTRAINT DESC_IMG_ID_fk FOREIGN KEY ("DESC_IMG_ID") REFERENCES "DATA_FILE" ("DATA_FILE_ID");

ALTER TABLE "PERSON" ADD CONSTRAINT EDUCATION_LEVEL_ID_fk FOREIGN KEY ("EDUCATION_LEVEL_ID") REFERENCES "EDUCATION_LEVEL" ("EDUCATION_LEVEL_ID");

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT ELECTRODE_CONF_ID_fk FOREIGN KEY ("ELECTRODE_CONF_ID") REFERENCES "ELECTRODE_CONF" ("ELECTRODE_CONF_ID");
ALTER TABLE "EXPERIMENT" ADD CONSTRAINT SUBJECT_GROUP_ID_fk FOREIGN KEY ("SUBJECT_GROUP_ID") REFERENCES "SUBJECT_GROUP" ("SUBJECT_GROUP_ID");
ALTER TABLE "EXPERIMENT" ADD CONSTRAINT ARTEFACT_ID_fk  FOREIGN KEY ("ARTEFACT_ID") REFERENCES "ARTEFACT" ("ARTEFACT_ID");
ALTER TABLE "EXPERIMENT" ADD CONSTRAINT DIGITALIZATION_ID_fk FOREIGN KEY ("DIGITALIZATION_ID") REFERENCES "DIGITALIZATION" ("DIGITALIZATION_ID");

ALTER TABLE "ARTEFACT_REMOVING_METHODS_REL" ADD CONSTRAINT EXPERIMENT_ID_fk FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPERIMENT_ID");
ALTER TABLE "ARTEFACT_REMOVING_METHODS_REL" ADD CONSTRAINT ARTEFACT_REMOVING_METHOD_ID_fk FOREIGN KEY ("ARTEFACT_REMOVING_METHOD_ID") REFERENCES "ARTEFACT_REMOVING_METHOD" ("ARTEFACT_REMOVING_METHOD_ID");

